# Data Preprocessing

### Imports

In [1]:
import sys
import os
import pandas as pd

### Load Dataset

In [2]:
# Allow the dataset to be loaded with both a Google Colab kernel and a local kernel

# Load the dataset with Google Colab kernel and Drive file
if 'google.colab' in sys.modules:
    # Time (aprox. 1m 30.0s)
    from pydrive2.auth import GoogleAuth
    from pydrive2.drive import GoogleDrive
    from google.colab import auth # type: ignore
    from oauth2client.client import GoogleCredentials

    # Authenticate the User in Google Drive
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)

    # Google Drive ID for public sharing of the dataset
    file_id = "1HLAenC73QhLDCVAvgIw_2Y54Gwcq5S0D"
    file = drive.CreateFile({'id': file_id})
    file.GetContentFile('raw_data.csv')

    # Reading the csv and loading it into a pandas dataframe (Use pyarrow to prevent OOM error when loading)
    df = pd.read_csv("raw_data.csv", engine="pyarrow", dtype_backend="pyarrow")

# Load the dataset with local kernel and local file
else:
    # Time (13th Gen Intel Core i5-1335U: aprox. 3.0s; AMD Ryzen AI 9 HX 370 (24) @ 5.16 GHz: aprox. 1.0s)
    # Reading the csv and loading it into a pandas dataframe (Use pyarrow to prevent OOM error when loading)
    df = pd.read_csv("../data/raw/raw_data.csv", engine="pyarrow", dtype_backend="pyarrow")

# Stop Jupyter Notebook from limiting the output
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Display dataset head
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,None,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68407277,<NA>,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,<NA>,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,<NA>,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,68355089,None,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68355089,<NA>,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,<NA>,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.66,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,<NA>,Mar-2019,699.0,695.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,<NA>,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,68341763,None,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68341763,<NA>,home_improvement,<NA>,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,<NA>,<NA>,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.0,2705.92,0.0,0.0,0.0,Jun-2017,15813.3,<NA>,Mar-2019,704.0,700.0,0.0,<NA>,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,<NA>,10.0,<NA>,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,66310712,None,35000.0,35000.0,35000.0,60 months,14.85,829.9,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=66310712,<NA>,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,<NA>,<NA>,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.01,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.9,Apr-2019,Mar-2019,679.0,675.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,<NA>,<NA>,<NA>,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,68476807,None,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68476807,<NA>,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,<NA>,12.0,0.0,21929.0,64.5,35.0,w,0.0,0.0,11740.5,11740.5,10400.0,1340.5,0.0,0.0,0.0,Jul-2016,10128.96,<NA>,Mar-2018,704.0,700.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

### Delete & Transform Columns & Rows

Display the missing values per column:

In [3]:
def print_column_info(df):
    # Get the total number of rows in the DataFrame
    total_rows = len(df)

    # Create the summary DataFrame
    data = pd.DataFrame({
        'Total (Null/Total)': df.isnull().sum().astype(str) + '/' + str(total_rows),
        'Percentage (%)': df.isnull().mean() * 100,
        'Data Type': df.dtypes
    })

    # Display the result
    display(data)

print_column_info(df)

,Total (Null/Total),Percentage (%),Data Type
id,0/2260701,0.000000,string[pyarrow]
member_id,2260701/2260701,100.000000,null[pyarrow]
loan_amnt,33/2260701,0.001460,double[pyarrow]
funded_amnt,33/2260701,0.001460,double[pyarrow]
funded_amnt_inv,33/2260701,0.001460,double[pyarrow]
term,33/2260701,0.001460,string[pyarrow]
int_rate,33/2260701,0.001460,double[pyarrow]
installment,33/2260701,0.001460,double[pyarrow]
grade,33/2260701,0.001460,string[pyarrow]
sub_grade,33/2260701,0.001460,string[pyarrow]
emp_title,167002/2260701,7.387178,string[pyarrow]
emp_length,146940/2260701,6.499754,string[pyarrow]
home_ownership,33/2260701,0.001460,string[pyarrow]
annual_inc,37/2260701,0.001637,double[pyarrow]
verification_status,33/2260701,0.001460,string[pyarrow]
issue_d,33/2260701,0.001460,string[pyarrow]
loan_status,33/2260701,0.001460,string[pyarrow]
pymnt_plan,33/2260701,0.001460,string[pyarrow]
url,33/2260701,0.001460,string[pyarrow]
desc,2134636/2260701,94.423632,string[pyarrow]
purpose,33/2260701,0.001460,string[pyarrow]
title,23359/2260701,1.033264,string[pyarrow]
zip_code,34/2260701,0.001504,string[pyarrow]
addr_state,33/2260701,0.001460,string[pyarrow]
dti,1744/2260701,0.077144,double[pyarrow]
delinq_2yrs,62/2260701,0.002743,double[pyarrow]
earliest_cr_line,62/2260701,0.002743,string[pyarrow]
fico_range_low,33/2260701,0.001460,double[pyarrow]
fico_range_high,33/2260701,0.001460,double[pyarrow]
inq_last_6mths,63/2260701,0.002787,double[pyarrow]
mths_since_last_delinq,1158535/2260701,51.246715,double[pyarrow]
mths_since_last_record,1901545/2260701,84.113069,double[pyarrow]
open_acc,62/2260701,0.002743,double[pyarrow]
pub_rec,62/2260701,0.002743,double[pyarrow]
revol_bal,33/2260701,0.001460,double[pyarrow]
revol_util,1835/2260701,0.081170,double[pyarrow]
total_acc,62/2260701,0.002743,double[pyarrow]
initial_list_status,33/2260701,0.001460,string[pyarrow]
out_prncp,33/2260701,0.001460,double[pyarrow]
out_prncp_inv,33/2260701,0.001460,double[pyarrow]
total_pymnt,33/2260701,0.001460,double[pyarrow]
total_pymnt_inv,33/2260701,0.001460,double[pyarrow]
total_rec_prncp,33/2260701,0.001460,double[pyarrow]
total_rec_int,33/2260701,0.001460,double[pyarrow]
total_rec_late_fee,33/2260701,0.001460,double[pyarrow]
recoveries,33/2260701,0.001460,double[pyarrow]
collection_recovery_fee,33/2260701,0.001460,double[pyarrow]
last_pymnt_d,2460/2260701,0.108816,string[pyarrow]
last_pymnt_amnt,33/2260701,0.001460,double[pyarrow]
next_pymnt_d,1345343/2260701,59.509993,string[pyarrow]
last_credit_pull_d,105/2260701,0.004645,string[pyarrow]
last_fico_range_high,33/2260701,0.001460,double[pyarrow]
last_fico_range_low,33/2260701,0.001460,double[pyarrow]
collections_12_mths_ex_med,178/2260701,0.007874,double[pyarrow]
mths_since_last_major_derog,1679926/2260701,74.309960,double[pyarrow]
policy_code,33/2260701,0.001460,double[pyarrow]
application_type,33/2260701,0.001460,string[pyarrow]
annual_inc_joint,2139991/2260701,94.660506,double[pyarrow]
dti_joint,2139995/2260701,94.660683,double[pyarrow]
verification_status_joint,2144971/2260701,94.880791,string[pyarrow]
acc_now_delinq,62/2260701,0.002743,double[pyarrow]
tot_coll_amt,70309/2260701,3.110053,double[pyarrow]
tot_cur_bal,70309/2260701,3.110053,double[pyarrow]
open_acc_6m,866163/2260701,38.313912,double[pyarrow]
open_act_il,866162/2260701,38.313868,double[pyarrow]
open_il_12m,866162/2260701,38.313868,double[pyarrow]
open_il_24m,866162/2260701,38.313868,double[pyarrow]
mths_since_rcnt_il,909957/2260701,40.251099,double[pyarrow]
total_bal_il,866162/2260701,38.313868,double[pyarrow]
il_util,1068883/2260701,47.281042,double[pyarrow]
open_rv_12m,866162/2260701,38.313868,double[pyarrow]
open_rv_24m,866162/2260701,38.313868,double[pyarrow]
max_bal_bc,866162/2260701,38.313868,double[pyarrow]
all_util,866381/2260701,38.323555,double[pyarrow]
total_rev_hi_lim,70309/2260701,3.110053,double[pyarrow]
inq_fi,866162/2260701,38.313868,double[pyarrow]
total_cu_tl,866163/2260701,38.313912,double[pyarrow]
inq_last_12m,866163/2260701,38.313912,double[pyarrow]
acc_open_past_24mths,50063/2260701,2.214490,double[pyarrow]
avg_cur_bal,70379/2260701,3.113149,double[pyarrow]
bc_open_to_buy,74968/2260701,3.316140,double[pyarrow]
bc_util,76104/2260701,3.366389,double[pyarrow]
chargeoff_within_12_mths,178/2260701,0.007874,double[pyarrow]
delinq_amnt,62/2260701,0.002743,double[pyarrow]
mo_sin_old_il_acct,139104/2260701,6.153136,double[pyarrow]
mo_sin_old_rev_tl_op,70310/2260701,3.110097,double[pyarrow]
mo_sin_rcnt_rev_tl_op,70310/2260701,3.110097,double[pyarrow]
mo_sin_rcnt_tl,70309/2260701,3.110053,double[pyarrow]
mort_acc,50063/2260701,2.214490,double[pyarrow]
mths_since_recent_bc,73445/2260701,3.248771,double[pyarrow]
mths_since_recent_bc_dlq,1741000/2260701,77.011511,double[pyarrow]
mths_since_recent_inq,295468/2260701,13.069751,double[pyarrow]
mths_since_recent_revol_delinq,1520342/2260701,67.250910,double[pyarrow]
num_accts_ever_120_pd,70309/2260701,3.110053,double[pyarrow]
num_actv_bc_tl,70309/2260701,3.110053,double[pyarrow]
num_actv_rev_tl,70309/2260701,3.110053,double[pyarrow]
num_bc_sats,58623/2260701,2.593134,double[pyarrow]
num_bc_tl,70309/2260701,3.110053,double[pyarrow]
num_il_tl,70309/2260701,3.110053,double[pyarrow]
num_op_rev_tl,70309/2260701,3.110053,double[pyarrow]
num_rev_accts,70310/2260701,3.110097,double[pyarrow]
num_rev_tl_bal_gt_0,70309/2260701,3.110053,double[pyarrow]
num_sats,58623/2260701,2.593134,double[pyarrow]
num_tl_120dpd_2m,153690/2260701,6.798334,double[pyarrow]
num_tl_30dpd,70309/2260701,3.110053,double[pyarrow]
num_tl_90g_dpd_24m,70309/2260701,3.110053,double[pyarrow]
num_tl_op_past_12m,70309/2260701,3.110053,double[pyarrow]
pct_tl_nvr_dlq,70464/2260701,3.116909,double[pyarrow]
percent_bc_gt_75,75412/2260701,3.335779,double[pyarrow]
pub_rec_bankruptcies,1398/2260701,0.061839,double[pyarrow]
tax_liens,138/2260701,0.006104,double[pyarrow]
tot_hi_cred_lim,70309/2260701,3.110053,double[pyarrow]
total_bal_ex_mort,50063/2260701,2.214490,double[pyarrow]
total_bc_limit,50063/2260701,2.214490,double[pyarrow]
total_il_high_credit_limit,70309/2260701,3.110053,double[pyarrow]
revol_bal_joint,2152681/2260701,95.221836,double[pyarrow]
sec_app_fico_range_low,2152680/2260701,95.221792,double[pyarrow]
sec_app_fico_range_high,2152680/2260701,95.221792,double[pyarrow]
sec_app_earliest_cr_line,2152680/2260701,95.221792,string[pyarrow]
sec_app_inq_last_6mths,2152680/2260701,95.221792,double[pyarrow]
sec_app_mort_acc,2152680/2260701,95.221792,double[pyarrow]
sec_app_open_acc,2152680/2260701,95.221792,double[pyarrow]
sec_app_revol_util,2154517/2260701,95.303050,double[pyarrow]
sec_app_open_act_il,2152680/2260701,95.221792,double[pyarrow]
sec_app_num_rev_accts,2152680/2260701,95.221792,double[pyarrow]
sec_app_chargeoff_within_12_mths,2152680/2260701,95.221792,double[pyarrow]
sec_app_collections_12_mths_ex_med,2152680/2260701,95.221792,double[pyarrow]
sec_app_mths_since_last_major_derog,2224759/2260701,98.410139,double[pyarrow]
hardship_flag,33/2260701,0.001460,string[pyarrow]
hardship_type,2249784/2260701,99.517097,string[pyarrow]
hardship_reason,2249784/2260701,99.517097,string[pyarrow]
hardship_status,2249784/2260701,99.517097,string[pyarrow]
deferral_term,2249784/2260701,99.517097,double[pyarrow]
hardship_amount,2249784/2260701,99.517097,double[pyarrow]
hardship_start_date,2249784/2260701,99.517097,string[pyarrow]
hardship_end_date,2249784/2260701,99.517097,string[pyarrow]
payment_plan_start_date,2249784/2260701,99.517097,string[pyarrow]
hardship_length,2249784/2260701,99.517097,double[pyarrow]
hardship_dpd,2249784/2260701,99.517097,double[pyarrow]
hardship_loan_status,2249784/2260701,99.517097,string[pyarrow]
orig_projected_additional_accrued_interest,2252050/2260701,99.617331,double[pyarrow]
hardship_payoff_balance_amount,2249784/2260701,99.517097,double[pyarrow]
hardship_last_payment_amount,2249784/2260701,99.517097,double[pyarrow]
disbursement_method,33/2260701,0.001460,string[pyarrow]
debt_settlement_flag,33/2260701,0.001460,string[pyarrow]
debt_settlement_flag_date,2226455/2260701,98.485160,string[pyarrow]
settlement_status,2226455/2260701,98.485160,string[pyarrow]
settlement_date,2226455/2260701,98.485160,string[pyarrow]
settlement_amount,2226455/2260701,98.485160,double[pyarrow]
settlement_percentage,2226455/2260701,98.485160,double[pyarrow]
settlement_term,2226455/2260701,98.485160,double[pyarrow]

Modify Rows:

In [4]:
# Before modifying the columns, we will delete the rows that are evidently erroneus in the .csv
# This will delete 33 rows that are weird and empty
display(df[df['loan_amnt'].isnull()])
df = df.dropna(subset=['loan_amnt'])

# This will delete 4 rows that are weird
display(df[df['annual_inc'].isnull()])
df = df.dropna(subset=['annual_inc'])

# This will delete 1 row that is weird
display(df[df['zip_code'].isnull()])
df = df.dropna(subset=['zip_code'])

# This will delete 25 rows that are weird
display(df[df['delinq_2yrs'].isnull()])
df = df.dropna(subset=['delinq_2yrs'])

# This will delete 1 row that is weird
display(df[df['inq_last_6mths'].isnull()])
df = df.dropna(subset=['inq_last_6mths'])

# This will delete 71 rows that are weird
display(df[df['last_credit_pull_d'].isnull()])
df = df.dropna(subset=['last_credit_pull_d'])

# This will delete 115 rows that are weird
display(df[df['collections_12_mths_ex_med'].isnull()])
df = df.dropna(subset=['collections_12_mths_ex_med'])

# The column we are trying to predict is loan_status, we will delete all rows that are "current" because it does not make sense to predict that a loan is still ongoing and we will also delete another 3 values that are clearly erroneous.
df = df[~df['loan_status'].isin(["Current", "Default", "Does not meet the credit policy. Status:Fully Paid", "Does not meet the credit policy. Status:Charged Off"])]
print_column_info(df)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
421095,Total amount funded in policy code 1: 6417608175,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
421096,Total amount funded in policy code 2: 1944088810,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
528961,Total amount funded in policy code 1: 1741781700,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
528962,Total amount funded in policy code 2: 564202131,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
651664,Total amount funded in policy code 1: 1791201400,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
651665,Total amount funded in policy code 2: 651669342,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
749520,Total amount funded in policy code 1: 1443412975,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
749521,Total amount funded in policy code 2: 511988838,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
877716,Total amount funded in policy code 1: 2063142975,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
877717,Total amount funded in policy code 2: 823319310,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
983169,Total amount funded in policy code 1: 1538432075,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
983170,Total amount funded in policy code 2: 608903141,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1117058,Total amount funded in policy code 1: 2087217200,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1117059,Total amount funded in policy code 2: 662815446,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1352689,Total amount funded in policy code 1: 3503840175,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1352690,Total amount funded in policy code 2: 873652739,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1481103,Total amount funded in policy code 1: 2050909275,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1481104,Total amount funded in policy code 2: 820109297,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1611877,Total amount funded in policy code 1: 2080429200,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1611878,Total amount funded in policy code 2: 737901574,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1651665,Loans that do not meet the credit policy,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
1654329,79967,None,5000.0,5000.0,3025.0,36 months,7.43,155.38,A,A2,<NA>,< 1 year,NONE,<NA>,Not Verified,Aug-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=79967,I will be relocating to Boston next month and am interested in financing my travel and moving expenses with a 3-year loan.,other,Moving expenses,100xx,NY,1.0,<NA>,<NA>,800.0,804.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,5593.631614,3384.14,5000.0,593.63,0.0,0.0,0.0,Aug-2010,157.31,Sep-2010,May-2007,804.0,800.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654330,79924,None,7000.0,7000.0,3450.0,36 months,7.75,218.55,A,A3,<NA>,< 1 year,NONE,<NA>,Not Verified,Aug-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=79924,"I am borrowing $7,000 for tuition and other expenses. Thank you for helping!",other,Education,100xx,NY,1.0,<NA>,<NA>,800.0,804.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,7867.655865,3877.63,7000.0,867.66,0.0,0.0,0.0,Aug-2010,220.03,Sep-2010,May-2007,804.0,800.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654360,79893,None,6700.0,6700.0,6700.0,36 months,7.75,209.18,A,A3,<NA>,< 1 year,NONE,<NA>,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=79893,"I am moving to Florida and would like to borrow $6,700 to cover for expenses and security deposit.",other,Moving expenses and security deposit,100xx,NY,1.0,<NA>,<NA>,800.0,804.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,7530.481427,7530.48,6700.0,830.48,0.0,0.0,0.0,Jul-2010,209.89,Aug-2010,May-2007,804.0,800.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654413,71623,None,6500.0,6500.0,0.0,36 months,8.38,204.84,A,A5,<NA>,< 1 year,NONE,<NA>,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=71623,"Hi, I'm buying a used car. Anybody on facebook wants to finance me? Thanks",other,Buying a car,100xx,NY,4.0,<NA>,<NA>,740.0,744.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,7373.904962,0.0,6500.0,873.9,0.0,0.0,0.0,Jun-2010,205.32,Jul-2010,Aug-2007,724.0,720.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
1736050,96387212,None,5600.0,5600.0,5600.0,36 months,15.99,196.86,C,C5,Electrician,10+ years,MORTGAGE,40000.0,Verified,Jan-2017,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=96387212,<NA>,debt_consolidation,Debt consolidation,<NA>,AL,22.86,0.0,Jul-2005,670.0,674.0,1.0,<NA>,107.0,8.0,1.0,7129.0,68.5,18.0,f,0.0,0.0,6895.874445,6895.87,5600.0,1295.87,0.0,0.0,0.0,Feb-2019,176.2,<NA>,Feb-2019,694.0,690.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,90183.0,1.0,3.0,0.0,6.0,15.0,10038.0,66.0,1.0,1.0,2363.0,67.0,10400.0,6.0,0.0,3.0,9.0,11273.0,3271.0,68.5,0.0,0.0,103.0,41.0,11.0,6.0,4.0,11.0,<NA>,6.0,<NA>,0.0,4.0,4.0,4.0,5.0,9.0,4.0,5.0,4.0,8.0,0.0,0.0,0.0,2.0,100.0,50.0,1.0,0.0,99094.0,17167.0,10400.0,15231.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
1654339,71823,None,4350.0,4350.0,825.0,36 months,8.07,136.45,A,A4,<NA>,< 1 year,RENT,120000.0,Not Verified,Aug-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=71823,"I owe $4,350 in medical bills not covered by my health insurance. I charged it to my credit card and would like to refinance it at a lower rate.",other,Paying medical bill,024xx,MA,4.0,<NA>,<NA>,740.0,744.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,4911.992738,931.59,4350.0,561.99,0.0,0.0,0.0,Aug-2010,139.93,Sep-2010,<NA>,0.0,0.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654352,72197,None,3900.0,3900.0,2025.0,36 months,9.33,124.62,B,B3,<NA>,< 1 year,RENT,98000.0,Not Verified,Aug-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=72197,I will be moving to Florida next month. This loan will help me pay for moving expenses. Thank you for funding me!,other,Moving to Florida,100xx,NY,10.0,<NA>,<NA>,705.0,709.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,4486.172967,2329.36,3900.0,586.17,0.0,0.0,0.0,Aug-2010,126.06,Sep-2010,May-2007,709.0,705.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654363,73003,None,3200.0,3200.0,2000.0,36 months,9.96,103.2,B,B5,<NA>,< 1 year,MORTGAGE,150000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=73003,"Hi, I am looking to renovate my bathroom as in the next year I want to sell my home. They say you can double your investment on a kitchen or bathroom when you sell the home, so I am hoping it gets me at least $5k on the sale price I have very good credit..thanks for looking Pistol",other,New Bathroom,019xx,MA,10.0,<NA>,<NA>,690.0,694.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,3590.587415,2244.12,3200.0,390.59,0.0,0.0,0.0,Feb-2009,1733.32,Mar-2009,Feb-2019,729.0,725.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654374,72819,None,7200.0,5075.0,350.0,36 months,10.28,164.42,C,C1,<NA>,< 1 year,RENT,95000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=72819,"I am consolidating 2 loans that carry 14.5% and 16% interest rate respectively. The first loan has $4,000 outstanding and the second has $3,200 outstanding. My credit is pretty good now so I am hoping I can get a better rate.",other,Consolidate 2 high-interest rate loans,100xx,NY,10.0,<NA>,<NA>,700.0,704.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,5918.938762,408.2,5075.0,843.94,0.0,0.0,0.0,Jul-2010,168.44,Aug-2010,May-2007,704.0,700.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654389,91023,None,1900.0,1900.0,900.0,36 months,9.64,61.0,B,B4,Scheduall,1 year,MORTGAGE,100000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=91023,Need to consolidate the credit cards - there had been few unexpected expenses that came up. I will be getting a new job soon and will be able to pay it back.,debt_consolidation,Consolidate credit cards,333xx,FL,10.0,<NA>,<NA>,705.0,709.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,1999.142676,946.97,1900.0,99.14,0.0,0.0,0.0,Feb-2008,0.0,Feb-2008,May-2007,709.0,705.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654394,85961,None,1200.0,1200.0,500.0,36 months,9.01,38.17,B,B2,Classic Components,< 1 year,RENT,36000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=85961,I am one month away from starting my new job in Austin. I recently graduated from the University of Texas at Austin's McCombs School of Business with a degree in Marketing. I am an account manager with Class-ic Components. I need a bridge loan until mid-July when I begin work.,other,College Debt Consolidation,787xx,TX,3.27,<NA>,<NA>,705.0,709.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,1373.990771,572.5,1200.0,173.99,0.0,0.0,0.0,Jul-2010,39.05,Jul-2010,Mar-2019,664.0,660.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654395,85818,None,5000.0,5000.0,375.0,36 months,11.22,164.23,C,C4,Compensation Solutions,< 1 year,RENT,28000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=85818,Getting my credit card debt paid off without having to worry about the high interest rate I am currently paying.,other,Credit Card,078xx,NJ,3.51,<NA>,<NA>,670.0,674.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,5858.468448,439.39,5000.0,828.47,30.0,0.0,0.0,Apr-2010,149.43,Apr-2010,Jan-2017,614.0,610.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654396,85781,None,1400.0,1400.0,475.0,36 months,10.91,45.78,C,C3,"Stanford University Libraries, LOCKSS Project",< 1 year,RENT,40000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=85781,"I'm starting full-time work as a programmer with Stanford University in a few weeks, but I need to move before my first paycheck. Most of the money will go to the deposit and first month's rent on an apartment.",other,Starting a new job in a new city,652xx,MO,8.61,<NA>,<NA>,670.0,674.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,1663.240931,564.31,1400.0,248.24,15.0,0.0,0.0,Jul-2010,1.78,Aug-2010,Sep-2014,679.0,675.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654397,85675,None,1000.0,1000.0,625.0,36 months,14.07,34.21,E,E3,Macy's,10+ years,RENT,25000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=85675,I have been working hard over the last few years to pay down my credit card debt. Just need a little more help getting rid of a few high interest cards.,other,Paying down high interest credit cards,080xx,NJ,16.27,<NA>,<NA>,640.0,644.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,1231.569372,769.73,1000.0,231.57,0.0,0.0,0.0,Jun-2010,35.27,Jul-2010,Mar-2018,629.0,625.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654398,84670,None,5000.0,5000.0,300.0,36 months,7.75,156.11,A,A3,Diamond Management and Technology Consultants,10+ years,MORTGAGE,300000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=84670,I want to follow my dream of photographing the wonderful underwater sights of Komodo and Sulawesi.,other,Indonesia Underwater Photography,701xx,LA,5.38,<NA>,<NA>,755.0,759.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,5565.731533,333.95,5000.0,565.73,0.0,0.0,0.0,Aug-2009,1663.91,Sep-2009,Aug-2009,759.0,755.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654399,84098,None,2500.0,2500.0,225.0,36 months,7.43,77.69,A,A2,U.S. Bank,9 years,MORTGAGE,66624.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=84098,loan to cover summer travel,other,vacation loan,452xx,OH,10.36,<NA>,<NA>,785.0,789.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,2600.243012,234.02,2500.0,100.24,0.0,0.0,0.0,Jan-2008,0.0,Jan-2008,Jun-2007,789.0,785.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654400,83979,None,3000.0,3000.0,250.0,36 months,7.43,93.23,A,A2,NC,1 year,MORTGAGE,80000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=83979,Need to relocate this money will help before I start my new job,other,Moving Expenses for relocation,070xx,NJ,0.39,<NA>,<NA>,795.0,799.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,3120.276572,260.02,3000.0,120.28,0.0,0.0,0.0,Jan-2008,0.0,Jan-2008,Jun-2007,799.0,795.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654401,83489,None,2600.0,2600.0,575.0,36 months,8.38,81.94,A,A5,College Pro Painters,3 years,MORTGAGE,6500.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Charged Off,n,https://lendingclub.com/browse/loanDetail.action?loan_id=83489,I would like to refinance my credit card debt to recieve a better rate on the money I owe.,other,Credit card refinancing,806xx,CO,6.46,<NA>,<NA>,720.0,724.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,2342.08,517.29,1962.69,329.05,21.64,28.7,0.34,Mar-2010,21.75,Mar-2010,Aug-2017,629.0,625.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654402,83185,None,1000.0,1000.0,625.0,36 months,7.12,30.94,A,A1,Mana Products,6 years,RENT,50000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=83185,I have a couple of credit cards and I am trying to borrow at lower overall rates.,other,Lowering My Interest Costs,100xx,NY,1.1,<NA>,<NA>,770.0,774.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,1113.503768,695.94,1000.0,113.5,0.0,0.0,0.0,Jun-2010,32.93,Jul-2010,Apr-2014,599.0,595.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654403,76629,None,1275.0,1275.0,0.0,36 months,12.49,42.65,D,D3,Infinitely law group,1 year,RENT,40000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Charged Off,n,https://lendingclub.com/browse/loanDetail.action?loan_id=76629,<NA>,other,Credit card debt,021xx,MA,10.0,<NA>,<NA>,705.0,709.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,1341.96,0.0,340.5,128.57,0.0,872.89,305.5105,May-2008,42.65,Dec-2008,Mar-2019,584.0,580.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1654404,74014,None,6450.0,6450.0,0.0,36 months,11.22,211.85,C,C4,Apto Solutions,2 years,RENT,32000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=74014,"I would like to pay off my credit card balances currently of $12,000. I'm paying an interest of 12% and would like to save by paying less interest. Thanks!",other,Credit Card Payments,303xx,GA,10.0,<NA>,<NA>,685.0,689.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,f,0.0,0.0,7798.618131,0.0,6450.0,1228.62,120.0,0.0,0.0,Jul-2010,167.78,Jul-2010,Jun-2010,574.0,570.0,<NA>,<NA>,1.0,Individual,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
1099335,69266577,None,35000.0,35000.0,35000.0,60 months,9.8,740.21,B,B3,Subcontracts Manager,10+ years,MORTGAGE,110000.0,Source Verified,Jan-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=69266577,<NA>,debt_consolidation,Debt consolidation,844xx,UT,20.09,0.0,Jun-1994,825.0,829.0,<NA>,<NA>,<NA>,10.0,0.0,1508.0,3.5,36.0,w,0.0,0.0,38962.991964,38962.99,35000.0,3962.99,0.0,0.0,0.0,Apr-2017,28619.11,<NA>,Mar-2019,809.0,805.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,235465.0,<NA>,5.0,1.0,4.0,4.0,43579.0,62.0,0.0,0.0,1508.0,40.0,43000.0,2.0,<NA>,<NA>,4.0,23547.0,28492.0,5.0,0.0,0.0,259.0,216.0,53.0,4.0,4.0,68.0,<NA>,12.0,<NA>,0.0,1.0,1.0,2.0,10.0,17.0,4.0,14.0,1.0,10.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,322518.0,45087.0,30000.0,69914.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
23249,66415157,None,14475.0,14475.0,14475.0,36 months,13.18,488.98,C,C3,Owner,10+ years,MORTGAGE,85000.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=66415157,<NA>,debt_consolidation,Debt consolidation,750xx,TX,15.39,0.0,Aug-2003,665.0,669.0,0.0,58.0,<NA>,8.0,0.0,6658.0,78.0,24.0,f,0.0,0.0,17576.598955,17576.6,14475.0,3101.6,0.0,0.0,0.0,Dec-2018,488.8,<NA>,<NA>,0.0,0.0,0.0,65.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,3528.0,17941.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8500.0,<NA>,<NA>,<NA>,2.0,2242.0,1700.0,78.0,0.0,0.0,112.0,134.0,49.0,10.0,0.0,49.0,<NA>,<NA>,<NA>,0.0,5.0,5.0,6.0,6.0,17.0,5.0,6.0,5.0,8.0,<NA>,0.0,0.0,1.0,92.0,40.0,0.0,0.0,32496.0,17941.0,8500.0,23996.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
70156,64220871,None,2400.0,2400.0,2400.0,36 months,11.49,79.14,B,B5,Customer Care,1 year,RENT,28000.0,Verified,Nov-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=64220871,<NA>,debt_consolidation,Debt consolidation,330xx,FL,34.8,0.0,Jun-2002,785.0,789.0,0.0,<NA>,<NA>,9.0,0.0,1543.0,9.0,14.0,w,0.0,0.0,2846.617526,2846.62,2400.0,446.62,0.0,0.0,0.0,Dec-2018,0.64,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,26287.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17300.0,<NA>,<NA>,<NA>,3.0,2920.0,3700.0,10.0,0.0,0.0,121.0,161.0,26.0,3.0,0.0,26.0,<NA>,11.0,<NA>,0.0,4.0,5.0,6.0,6.0,5.0,5.0,9.0,2.0,9.0,<NA>,0.0,0.0,3.0,100.0,0.0,0.0,0.0,50154.0,26287.0,14800.0,32854.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
82296,63569464,None,12000.0,12000.0,11825.0,60 months,25.78,357.73,F,F5,Support Specialist,2 years,RENT,45000.0,Verified,Nov-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=63569464,<NA>,credit_card,Credit card refinancing,300xx,GA,22.99,0.0,May-2011,660.0,664.0,1.0,<NA>,<NA>,8.0,0.0,16755.0,79.0,9.0,f,0.0,0.0,19255.913906,18975.1,12000.0,7255.91,0.0,0.0,0.0,Oct-2018,4118.87,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,51141.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,21250.0,<NA>,<NA>,<NA>,2.0,6392.0,7083.0,79.0,0.0,0.0,32.0,53.0,15.0,9.0,0.0,15.0,<NA>,0.0,<NA>,0.0,3.0,3.0,3.0,3.0,5.0,3.0,4.0,3.0,8.0,<NA>,0.0,0.0,1.0,100.0,33.3,0.0,0.0,56179.0,51141.0,21250.0,34929.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
353800,42384466,None,16000.0,16000.0,16000.0,36 months,5.93,486.25,A,A1,Salon Lead,2 years,RENT,60000.0,Not Verified,Mar-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=42384466,<NA>,debt_consolidation,Debt consolidation,334xx,FL,27.68,0.0,Nov-1984,775.0,779.0,2.0,30.0,<NA>,11.0,0.0,627.0,1.0,29.0,f,0.0,0.0,17499.481933,17499.48,16000.0,1499.48,0.0,0.0,0.0,Mar-2018,486.0,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,37028.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,64000.0,<NA>,<NA>,<NA>,3.0,3366.0,9167.0,1.0,0.0,0.0,29.0,364.0,14.0,12.0,4.0,14.0,30.0,4.0,30.0,0.0,6.0,9.0,13.0,14.0,2.0,9.0,24.0,1.0,11.0,<NA>,0.0,0.0,1.0,97.0,0.0,0.0,0.0,115394.0,37028.0,55000.0,51394.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
382232,40481576,None,14000.0,14000.0,14000.0,36 months,10.49,454.97,B,B3,owner,10+ years,OWN,60000.0,Verified,Mar-2015,Charged Off,n,https://lendingclub.com/browse/loanDetail.action?loan_id=40481576,<NA>,debt_consolidation,Debt consolidation,800xx,CO,15.84,0.0,May-1992,675.0,679.0,3.0,62.0,63.0,16.0,1.0,1008.0,3.7,48.0,f,0.0,0.0,6135.37,6135.37,5452.51,682.86,0.0,0.0,0.0,Oct-2015,454.97,<NA>,<NA>,0.0,0.0,0.0,62.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,49810.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,27500.0,<NA>,<NA>,<NA>,9.0,3832.0,14817.0,4.4,0.0,0.0,272.0,244.0,2.0,2.0,0.0,6.0,<NA>,0.0,<NA>,1.0,1.0,2.0,7.0,22.0,15.0,13.0,31.0,2.0,14.0,0.0,0.0,0.0,4.0,97.1,0.0,1.0,0.0,81879.0,49810.0,15500.0,54379.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
387348,40267469,None,8150.0,8150.0,8150.0,36 months,15.59,284.89,D,D1,Teacher,6 years,RENT,37900.0,Source Verified,Feb-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=40267469,<NA>,debt_consolidation,Debt consolidation,376xx,TN,19.63,0.0,Dec-1996,665.0,669.0,0.0,<NA>,38.0,5.0,1.0,0.0,0.0,15.0,f,0.0,0.0,9986.230062,9986.23,8150.0,1836.23,0.0,0.0,0.0,Feb-2017,3440.82,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,2359.0,19967.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1800.0,<NA>,<NA>,<NA>,4.0,3993.0,1200.0,0.0,0.0,0.0,162.0,217.0,19.0,2.0,0.0,89.0,<NA>,12.0,<NA>,0.0,0.0,0.0,1.0,3.0,11.0,2.0,4.0,0.0,5.0,0.0,0.0,0.0,2.0,100.0,0.0,1.0,0.0,27348.0,19967.0,1200.0,25548.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
419796,37722220,None,35000.0,35000.0,35000.0,36 months,10.49,1137.43,B,B3,VP Marketing and Business Development,8 years,OWN,223000.0,Source Verified,Jan-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=37722220,<NA>,credit_card,Credit card refinancing,017xx,MA,20.28,1.0,Jan-1994,725.0,729.0,0.0,20.0,<NA>,9.0,0.0,41497.0,11.3,32.0,f,0.0,0.0,40906.289861,40906.29,35000.0,5906.29,0.0,0.0,0.0,Jan-2018,1137.03,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,552227.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,61400.0,<NA>,<NA>,<NA>,1.0,61359.0,16959.0,8.4,0.0,0.0,106.0,251.0,0.0,0.0,6.0,0.0,35.0,<NA>,20.0,0.0,3.0,5.0,4.0,12.0,5.0,6.0,19.0,5.0,9.0,0.0,0.0,0.0,1.0,87.5,25.0,0.0,0.0,640507.0,129704.0,57600.0,35169.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
425298,130610158,None,7000.0,7000.0,7000.0,36 months,10.9,228.84,B,B4,Truck Driver,8 years,RENT,60000.0,Source Verified,Mar-2018,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=130610158,<NA>,credit_card,Credit card refinancing,346xx,FL,32.14,0.0,Jun-2005,710.0,714.0,2.0,<NA>,<NA>,10.0,0.0,30720.0,53.0,27.0,w,4914.95,4914.95,2741.84,2741.84,2085.05,656.79,0.0,0.0,0.0,Mar-2019,228.84,Apr-2019,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,42909.0,2.0,1.0,0.0,1.0,21.0,12189.0,49.0,2.0,3.0,12110.0,53.0,58200.0,0.0,0.0,2.0,4.0,4290.0,7867.0,79.0,0.0,0.0,136.0,153.0,4.0,4.0,0.0,4.0,<NA>,4.0,<NA>,0.0,3.0,9.0,5.0,5.0,5.0,9.0,22.0,8.0,10.0,<NA>,0.0,0.0,2.0,100.0,66.7,0.0,0.0,82950.0,42909.0,23600.0,24750.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
586434,116253252,None,3200.0,3200.0,3200.0,36 months,7.97,100.24,A,A5,Receptionist,1 year,RENT,20000.0,Not Verified,Aug-2017,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=116253252,<NA>,credit_card,Credit card refinancing,440xx,OH,27.19,0.0,Oct-2012,755.0,759.0,0.0,<NA>,<NA>,8.0,0.0,3656.0,12.0,10.0,w,1606.08,1606.08,1901.73,1901.73,1593.92,307.81,0.0,0.0,0.0,Mar-2019,100.24,Apr-2019,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,7183.0,0.0,1.0,0.0,0.0,15.0,3527.0,28.0,0.0,2.0,2060.0,12.0,30200.0,0.0,0.0,0.0,2.0,897.0,5000.0,12.0,0.0,0.0,58.0,56.0,16.0,15.0,0.0,16.0,<NA>,22.0,<NA>,0.0,6.0,7.0,6.0,6.0,3.0,7.0,7.0,3.0,8.0,<NA>,0.0,0.0,0.0,100.0,0.0,0.0,0.0,42898.0,7183.0,30000.0,12698.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
660738,83313517,None,24000.0,24000.0,24000.0,36 months,5.32,722.76,A,A1,Financial Comptroller,10+ years,MORTGAGE,90000.0,Verified,Jun-2016,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=83313517,<NA>,credit_card,Credit card refinancing,309xx,GA,17.95,0.0,Mar-1997,715.0,719.0,0.0,<NA>,<NA>,10.0,0.0,43003.0,37.0,16.0,w,1802.56,1802.56,24143.99,24143.99,22197.44,1946.55,0.0,0.0,0.0,Mar-2019,722.76,Apr-2019,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,218899.0,1.0,0.0,0.0,0.0,43.0,0.0,0.0,1.0,1.0,32420.0,37.0,115550.0,0.0,0.0,0.0,1.0,21889.0,17700.0,36.0,0.0,0.0,122.0,231.0,1.0,1.0,3.0,68.0,<NA>,<NA>,<NA>,0.0,6.0,9.0,7.0,7.0,3.0,9.0,10.0,6.0,10.0,<NA>,0.0,0.0,1.0,100.0,33.3,0.0,0.0,315550.0,43003.0,106200.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
681703,80740687,None,24750.0,24750.0,24700.0,36 months,12.99,833.81,C,C2,Truck Driver,5 years,RENT,55000.0,Verified,Jun-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=80740687,<NA>,debt_consolidation,Debt consolidation,346xx,FL,21.71,0.0,Jun-2005,685.0,689.0,0.0,<NA>,<NA>,16.0,0.0,29210.0,54.0,23.0,f,0.0,0.0,29687.248259,29627.27,24750.0,4937.25,0.0,0.0,0.0,Dec-2018,724.62,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,31942.0,1.0,1.0,1.0,1.0,5.0,2732.0,84.0,1.0,2.0,6407.0,54.0,54050.0,0.0,0.0,2.0,3.0,1996.0,5213.0,74.0,0.0,0.0,114.0,131.0,9.0,5.0,0.0,91.0,<NA>,5.0,<NA>,0.0,4.0,15.0,4.0,4.0,4.0,15.0,19.0,12.0,16.0,<NA>,0.0,0.0,2.0,100.0,50.0,0.0,0.0,57294.0,31942.0,20850.0,3244.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
782828,139349331,None,16000.0,16000.0,16000.0,36 months,13.56,543.43,C,C1,Manager,3 years,OWN,69996.0,Not Verified,Sep-2018,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=139349331,<NA>,debt_consolidation,Debt consolidation,123xx,NY,17.71,1.0,Feb-2015,660.0,664.0,0.0,9.0,<NA>,12.0,0.0,16420.0,51.2,14.0,w,13761.82,13761.82,3236.47,3236.47,2238.18,998.29,0.0,0.0,0.0,Mar-2019,543.43,Apr-2019,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,46678.0,1.0,1.0,1.0,1.0,3.0,30258.0,98.0,0.0,3.0,4193.0,74.0,32100.0,1.0,0.0,6.0,4.0,3890.0,13480.0,54.9,0.0,0.0,32.0,42.0,14.0,3.0,0.0,14.0,<NA>,2.0,9.0,0.0,8.0,8.0,8.0,8.0,2.0,11.0,11.0,8.0,12.0,0.0,0.0,0.0,1.0,92.9,25.0,0.0,0.0,63032.0,46678.0,29900.0,30932.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,DirectPay,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
820845,137984341,None,2000.0,2000.0,2000.0,36 months,18.94,73.26,D,D2,Sales Manager,5 years,MORTGAGE,38500.0,Not Verified,Aug-2018,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=137984341,<NA>,home_improvement,Home improvement,379xx,TN,17.55,1.0,Jan-2002,690.0,694.0,1.0,9.0,<NA>,8.0,0.0,8168.0,64.0,20.0,w,0.0,0.0,2125.765652,2125.77,2000.0,125.77,0.0,0.0,0.0,Dec-2018,1910.2,<NA>,<NA>,0.0,0.0,0.0,79.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,172837.0,0.0,1.0,0.0,0.0,29.0,14201.0,70.0,0.0,0.0,2746.0,64.0,12800.0,0.0,0.0,1.0,0.0,24691.0,1833.0,94.0,0.0,0.0,29.0,199.0,30.0,29.0,4.0,30.0,9.0,0.0,9.0,0.0,3.0,5.0,4.0,7.0,1.0,5.0,15.0,5.0,7.0,<NA>,0.0,0.0,0.0,85.0,100.0,0.0,0.0,190781.0,25503.0,5500.0,20256.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
862514,136432293,None,7500.0,7500.0,7500.0,36 months,17.97,271.04,D,D1,<NA>,<NA>,OWN,76000.0,Source Verified,Jul-2018,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=136432293,<NA>,home_improvement,Home improvement,291xx,SC,19.07,0.0,Nov-2001,710.0,714.0,0.0,<NA>,<NA>,5.0,0.0,17688.0,80.0,9.0,w,0.0,0.0,8192.411672,8192.41,7500.0,692.41,0.0,0.0,0.0,Feb-2019,6618.76,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,56540.0,0.0,1.0,0.0,1.0,16.0,38852.0,82.0,0.0,0.0,7208.0,80.0,22100.0,0.0,0.0,1.0,1.0,11308.0,5367.0,100.0,0.0,0.0,155.0,192.0,42.0,16.0,1.0,124.0,<NA>,11.0,<NA>,0.0,3.0,4.0,4.0,4.0,2.0,4.0,6.0,4.0,5.0,<NA>,0.0,0.0,0.0,100.0,100.0,0.0,0.0,69735.0,56540.0,16100.0,47635.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
995163,75407451,None,12075.0,12075.0,12075.0,36 months,12.99,406.8,C,C2,Owner,3 years,RENT,85000.0,Source Verified,Mar-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=75407451,<NA>,car,Car financing,073xx,NJ,15.13,1.0,Nov-2002,660.0,664.0,1.0,<NA>,4.0,8.0,1.0,3456.0,51.0,18.0,w,0.0,0.0,14244.621024,14244.62,12075.0,2169.62,0.0,0.0,0.0,Feb-2018,5710.53,<NA>,<NA>,0.0,0.0,0.0,13.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,19043.0,0.0,1.0,0.0,0.0,26.0,15587.0,71.0,0.0,2.0,1604.0,51.0,6800.0,1.0,0.0,3.0,2.0,2380.0,1200.0,53.0,1.0,0.0,141.0,160.0,14.0,14.0,0.0,14.0,<NA>,4.0,<NA>,2.0,5.0,7.0,5.0,5.0,5.0,7.0,13.0,7.0,8.0,<NA>,0.0,1.0,0.0,67.0,20.0,0.0,0.0,28663.0,19043.0,6000.0,21863.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1030189,73933742,None,7000.0,7000.0,7000.0,36 months,9.16,223.12,B,B2,purchasing,2 years,RENT,55000.0,Not Verified,Mar-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=73933742,<NA>,debt_consolidation,Debt consolidation,983xx,WA,16.67,1.0,Mar-1993,675.0,679.0,0.0,23.0,<NA>,7.0,0.0,8940.0,90.0,16.0,w,0.0,0.0,7859.224134,7859.22,7000.0,859.22,0.0,0.0,0.0,Jan-2018,3177.26,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,12304.0,0.0,2.0,0.0,0.0,54.0,3364.0,17.0,0.0,0.0,3103.0,90.0,9900.0,0.0,2.0,0.0,0.0,1757.0,1980.0,90.0,0.0,0.0,182.0,276.0,54.0,54.0,0.0,54.0,23.0,21.0,23.0,0.0,5.0,5.0,3.0,6.0,7.0,5.0,9.0,5.0,7.0,<NA>,0.0,0.0,0.0,75.0,100.0,0.0,0.0,29950.0,12304.0,9900.0,20050.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1133016,35186548,None,1500.0,1500.0,1500.0,36 months,11.44,49.43,B,B4,director of marketing/commercial realtor,10+ years,RENT,120000.0,Source Verified,Nov-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=35186548,<NA>,major_purchase,Major purchase,386xx,MS,1.94,0.0,Jun-1995,675.0,679.0,0.0,57.0,60.0,4.0,1.0,880.0,27.0,27.0,f,0.0,0.0,1760.761208,1760.76,1500.0,260.76,0.0,0.0,0.0,Mar-2017,227.1,<NA>,<NA>,0.0,0.0,0.0,56.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,4400.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3250.0,<NA>,<NA>,<NA>,1.0,1100.0,1125.0,19.0,0.0,0.0,142.0,233.0,24.0,23.0,2.0,32.0,63.0,7.0,63.0,0.0,2.0,3.0,5.0,10.0,6.0,3.0,19.0,3.0,4.0,<NA>,0.0,0.0,0.0,56.0,0.0,1.0,0.0,19954.0,4400.0,2250.0,16704.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1143258,34473266,None,12000.0,12000.0,12000.0,36 months,11.44,395.37,B,B4,Special Assist to the Dean and President,2 years,RENT,85000.0,Source Verified,Nov-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=34473266,<NA>,debt_consolidation,Debt consolidation,100xx,NY,9.93,0.0,Jul-1996,700.0,704.0,1.0,<NA>,<NA>,8.0,0.0,11529.0,64.0,9.0,w,0.0,0.0,12995.33,12995.33,12000.0,995.33,0.0,0.0,0.0,Aug-2015,9851.44,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,21852.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18100.0,<NA>,<NA>,<NA>,3.0,3121.0,3280.0,68.0,0.0,0.0,85.0,220.0,10.0,8.0,0.0,10.0,<NA>,4.0,<NA>,0.0,5.0,6.0,5.0,5.0,2.0,6.0,7.0,5.0,7.0,<NA>,0.0,0.0,2.0,100.0,40.0,0.0,0.0,30100.0,21852.0,16400.0,12000.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1143428,34493159,None,19750.0,19750.0,19750.0,60 months,12.99,449.28,C,C2,Workers Compensation Insurance Technicia,10+ years,RENT,44136.0,Verified,Nov-2014,Charged Off,n,https://lendingclub.com/browse/loanDetail.action?loan_id=34493159,<NA>,debt_consolidation,Debt consolidation,936xx,CA,27.62,0.0,Nov-1996,735.0,739.0,0.0,<NA>,<NA>,10.0,0.0,8397.0,35.0,20.0,w,0.0,0.0,6743.6,6743.6,1956.83,1616.03,0.0,3170.74,285.3666,Jul-2015,449.28,<NA>,<NA>,0.0,0.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,71132.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,24250.0,<NA>,<NA>,<NA>,4.0,7113.0,6375.0,43.0,0.0,0.0,210.0,216.0,7.0,7.0,0.0,7.0,71.0,7.0,71.0,0.0,2.0,6.0,4.0,5.0,9.0,6.0,11.0,5.0,10.0,<NA>,0.0,0.0,3.0,95.0,50.0,0.0,0.0,100812.0,71132.0,12750.0,76562.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

             id member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
1651577  131387      None     6000.0       6000.0            600.0
1651590  127213      None     2000.0       2000.0           1575.0
1651598   84918      None     5000.0       5000.0           2025.0
1651607  121568      None     4000.0       4000.0           1925.0
1651608  121535      None     2800.0       2800.0           1625.0
1651614  119043      None    15450.0      15450.0            600.0
1651615  118823      None     2500.0       2500.0            675.0
1651616  118533      None     2500.0       2500.0            825.0
1651617  118523      None     6500.0       6500.0            225.0
1651618  117863      None     8000.0       8000.0           2275.0
1651619  117794      None     7500.0       7500.0            400.0
1651620  117249      None     5000.0       5000.0           1300.0
1651621  117056      None     5000.0       5000.0           1475.0
1651622  116582      None    10000.0      10000.0            975.0
1651623  116040      None     5000.0       5000.0            775.0
1651624   88854      None     5000.0       5000.0            225.0
1651625  113194      None     3500.0       3500.0           1725.0
1651626  113179      None     1000.0       1000.0            950.0
1651627  113156      None     3500.0       3500.0           3500.0
1651628  112496      None     3000.0       3000.0            525.0
1651629  112323      None     3500.0       3500.0           1125.0
1651630   99009      None     5750.0       5750.0           3675.0
1651631  112245      None     5000.0       5000.0           3975.0
1651632  112216      None    12000.0      12000.0           1025.0
1651633  100214      None     5000.0       5000.0           3675.0
1651634  111917      None     6400.0       6400.0           4075.0
1651635  111307      None    12000.0      12000.0           2500.0
1651636  111227      None    20000.0      20000.0           2800.0
1651637  109355      None     1200.0       1200.0              0.0
1651638  107136      None    12250.0      12250.0           1525.0
1651639  106360      None     2700.0       2700.0            550.0
1651640   76597      None     5000.0       5000.0           1775.0
1651641  106079      None     3500.0       3500.0           1200.0
1651642   90966      None     5000.0       5000.0           4150.0
1651643   92440      None     5000.0       5000.0           3100.0
1651644  102376      None    25000.0      25000.0            525.0
1651645  101579      None    10000.0      10000.0            400.0
1651646   98982      None     5000.0       5000.0            675.0
1651647   98339      None     5100.0       5100.0            575.0
1651648   98276      None     5400.0       5400.0            200.0
1651649   96844      None     5300.0       5300.0            600.0
1651650   96350      None     5000.0       5000.0            850.0
1651651   94838      None     3000.0       3000.0           2550.0
1651652   93277      None     3000.0       3000.0            950.0
1651653   93061      None     5000.0       5000.0            250.0
1651654   92676      None     5000.0       5000.0            150.0
1651655   92666      None     5000.0       5000.0            525.0
1651656   92552      None     5000.0       5000.0            375.0
1651657   92533      None     5000.0       5000.0            675.0
1651658   92507      None     5000.0       5000.0            250.0
1651659   92402      None     5000.0       5000.0            700.0
1651660   92187      None     2500.0       2500.0           1075.0
1651661   90665      None     8500.0       8500.0            875.0
1651662   90395      None     5000.0       5000.0           1325.0
1651663   90376      None     5000.0       5000.0            650.0
1651664   87023      None     7500.0       7500.0            800.0
1654271  127606      None     5000.0       5000.0           1100.0
1654312  124624      None     4000.0       4000.0           2675.0
1654326  117045      None     3500.0       3500.0           2225.0
1654331  119948      None     3750.0       3750.0            250.0
1654332  119360      None     8950.0       8950.0           3650.0
1654333  119262      None     5700.0       5700.0           1450.0
1654334  119071      None     5000.0       5000.0            725.0
1654335  118872      None     8950.0       8950.0            500.0
1654336  118367      None    16225.0      16225.0            475.0
1654337  118024      None     5000.0       5000.0            750.0
1654338  117192      None     2500.0       2500.0           1125.0
1654340  116129      None     2000.0       2000.0           1775.0
1654341  115606      None    12800.0      12800.0           1000.0
1654342  115602      None    25000.0       9550.0            800.0
1654343  115363      None    25000.0      13750.0            825.0
1654344  114943      None     6000.0       6000.0           5575.0
1654345  114838      None     6000.0       6000.0           1025.0
1654346  114642      None    19000.0      19000.0           1450.0
1654347  114511      None    12000.0      12000.0            850.0
1654348  114469      None    13000.0      13000.0            825.0
1654349  114408      None     8000.0       8000.0           1400.0
1654350  114333      None    10000.0      10000.0           1775.0
1654351  114133      None     8000.0       8000.0           4025.0
1654353  113450      None    13000.0      13000.0            700.0
1654354  113231      None     5000.0       5000.0           1075.0
1654355  113203      None    10500.0      10500.0           1125.0
1654356  112806      None     2000.0       2000.0           1000.0
1654357  112747      None     3000.0       3000.0           1300.0
1654358  111868      None     3500.0       3500.0           2575.0
1654359  111564      None     4100.0       4100.0           2775.0
1654361  110627      None     1000.0       1000.0            850.0
1654364  108473      None     1200.0       1200.0            700.0
1654365  107560      None     3200.0       3200.0           1250.0
1654366  106216      None     2000.0       2000.0            100.0
1654367  104634      None     9000.0       9000.0           1425.0
1654368  104530      None     1250.0       1250.0             75.0
1654369  103846      None     5000.0       5000.0           1100.0
1654370  103507      None     4000.0       4000.0            625.0
1654371  103478      None     1800.0       1800.0            300.0
1654372  102823      None     4500.0       4500.0           1325.0
1654373   72323      None     5000.0       5000.0            350.0
1654375  100134      None     1000.0       1000.0            500.0
1654376   99987      None     1200.0       1200.0            550.0
1654377   99982      None    10000.0      10000.0            525.0
1654378   99634      None     4000.0       4000.0            325.0
1654379   99100      None    15600.0       8000.0            775.0
1654380   98984      None     3500.0       3500.0           1025.0
1654381   98360      None     2600.0       2600.0            950.0
1654382   97606      None    10500.0       4000.0           1150.0
1654383   95250      None    10000.0      10000.0           1450.0
1654384   95198      None    20000.0      20000.0            700.0
1654385   94406      None     6725.0       6725.0            825.0
1654386   93055      None     2000.0       2000.0           1025.0
1654387   91175      None     6000.0       6000.0           1200.0
1654388   91126      None     5350.0       5350.0            625.0
1654390   90106      None    10000.0      10000.0            350.0
1654391   89258      None     2000.0       2000.0           1275.0
1654392   88637      None     6000.0       6000.0            650.0
1654393   88046      None     4400.0       4400.0           1400.0

               term  int_rate  installment grade sub_grade  \
1651577   36 months     10.59       195.27     C        C2
1651590   36 months      7.12        61.87     A        A1
1651598   36 months      7.43       155.38     A        A2
1651607   36 months      9.64       128.41     B        B4
1651608   36 months       8.7        88.65     B        B1
1651614   36 months     11.22       507.46     C        C4
1651615   36 months      12.8         84.0     D        D4
1651616   36 months      9.64        80.26     B        B4
1651617   36 months     15.01       225.37     F        F1
1651618   36 months      9.96       257.99     B        B5
1651619   36 months      8.07       235.25     A        A4
1651620   36 months      7.43       155.38     A        A2
1651621   36 months      7.75       156.11     A        A3
1651622   36 months     13.75       340.57     E        E2
1651623   36 months      9.64       160.51     B        B4
1651624   36 months      7.43       155.38     A        A2
1651625   36 months      9.96       112.87     B        B5
1651626   36 months     10.59        32.55     C        C2
1651627   36 months      8.07       109.79     A        A4
1651628   36 months     11.86        99.44     D        D1
1651629   36 months     10.28       113.39     C        C1
1651630   36 months      7.43       178.69     A        A2
1651631   36 months      7.43       155.38     A        A2
1651632   36 months     11.86       397.75     D        D1
1651633   36 months      7.43       155.38     A        A2
1651634   36 months      9.64       205.45     B        B4
1651635   36 months     12.49       401.37     D        D3
1651636   36 months     13.43       678.08     E        E1
1651637   36 months     11.54         39.6     C        C5
1651638   36 months     10.59       398.69     C        C2
1651639   36 months     15.96        94.88     F        F4
1651640   36 months      9.01       159.03     B        B2
1651641   36 months      9.96       112.87     B        B5
1651642   36 months      7.43       155.38     A        A2
1651643   36 months      7.43       155.38     A        A2
1651644   36 months     10.59       813.65     C        C2
1651645   36 months     10.28       323.98     C        C1
1651646   36 months      9.01       159.03     B        B2
1651647   36 months      8.38       160.72     A        A5
1651648   36 months      7.75        168.6     A        A3
1651649   36 months      8.38       167.02     A        A5
1651650   36 months     11.22       164.23     C        C4
1651651   36 months     10.28         97.2     C        C1
1651652   36 months       8.7        94.98     B        B1
1651653   36 months      7.43       155.38     A        A2
1651654   36 months      8.07       156.84     A        A4
1651655   36 months      9.33       159.77     B        B3
1651656   36 months      9.96       161.25     B        B5
1651657   36 months     11.22       164.23     C        C4
1651658   36 months      7.43       155.38     A        A2
1651659   36 months       8.7        158.3     B        B1
1651660   36 months      8.07        78.42     A        A4
1651661   36 months     10.28       275.38     C        C1
1651662   36 months      8.07       156.84     A        A4
1651663   36 months      7.43       155.38     A        A2
1651664   36 months     13.75       255.43     E        E2
1654271   36 months     12.49       167.24     D        D3
1654312   36 months      9.33       127.82     B        B3
1654326   36 months      7.43       108.77     A        A2
1654331   36 months     15.65       131.19     F        F3
1654332   36 months      9.64        287.3     B        B4
1654333   36 months     13.43       193.26     E        E1
1654334   36 months      14.7       172.59     E        E5
1654335   36 months     16.91       318.69     G        G2
1654336   36 months     17.86       585.41     G        G5
1654337   36 months     13.75       170.29     E        E2
1654338   36 months      9.96        80.63     B        B5
1654340   36 months      8.38        63.03     A        A5
1654341   36 months     15.01       443.81     F        F1
1654342   36 months     15.33        332.6     F        F2
1654343   36 months     16.91       489.61     G        G2
1654344   36 months     10.91       196.18     C        C3
1654345   36 months      12.8        201.6     D        D4
1654346   36 months     16.28       670.59     F        F5
1654347   36 months     14.38       412.37     E        E4
1654348   36 months     17.22       464.95     G        G3
1654349   36 months     16.91       284.86     G        G2
1654350   36 months     15.01       346.73     F        F1
1654351   36 months      9.96       257.99     B        B5
1654353   36 months     10.91       425.04     C        C3
1654354   36 months     14.07       171.05     E        E3
1654355   36 months     15.33       365.69     F        F2
1654356   36 months     13.43        67.81     E        E1
1654357   36 months     13.75       102.17     E        E2
1654358   36 months     12.17       116.54     D        D2
1654359   36 months     10.59       133.44     C        C2
1654361   36 months     15.01        34.68     F        F1
1654364   36 months     17.54        43.11     G        G4
1654365   36 months      14.7       110.46     E        E5
1654366   36 months     14.38        68.73     E        E4
1654367   36 months     15.96       316.25     F        F4
1654368   36 months     14.38        42.96     E        E4
1654369   36 months     11.22       164.23     C        C4
1654370   36 months     15.33       139.31     F        F2
1654371   36 months     14.38        61.86     E        E4
1654372   36 months     12.49       150.52     D        D3
1654373   36 months     11.54       164.98     C        C5
1654375   36 months     12.49        33.45     D        D3
1654376   36 months     10.28        38.88     C        C1
1654377   36 months      14.7       345.18     E        E5
1654378   36 months     13.12       135.01     D        D5
1654379   36 months     11.86       265.17     D        D1
1654380   36 months     10.91       114.44     C        C3
1654381   36 months     14.38        89.35     E        E4
1654382   36 months     16.91       142.43     G        G2
1654383   36 months     10.59       325.46     C        C2
1654384   36 months     15.01       693.45     F        F1
1654385   36 months     13.12       226.98     D        D5
1654386   36 months      12.8         67.2     D        D4
1654387   36 months     13.12       202.51     D        D5
1654388   36 months     13.12       180.57     D        D5
1654390   36 months      14.7       345.18     E        E5
1654391   36 months      7.12        61.87     A        A1
1654392   36 months     10.59       195.28     C        C2
1654393   36 months      9.64       141.25     B        B4

                                              emp_title emp_length  \
1651577                             Columbia University    2 years
1651590                                 U.S. Government  10+ years
1651598                           Revere Public Schools  10+ years
1651607                                            <NA>   < 1 year
1651608                                            <NA>   < 1 year
1651614                                            ARIN    2 years
1651615                   Nebraska Occupational Therapy   < 1 year
1651616                                   AMZ Marketing   < 1 year
1651617                           Universal Advertising    9 years
1651618                                     Inglis Farm    3 years
1651619                              Alliance Financial     1 year
1651620                                            <NA>   < 1 year
1651621                     Otolaryngology/ENT Practice     1 year
1651622                                            <NA>   < 1 year
1651623                        MasterCard International    3 years
1651624                               Rail Europe Group    4 years
1651625         Aramis Designer Fragrances/Estee Lauder     1 year
1651626                         Invision Power Services    2 years
1651627                                         Verizon    5 years
1651628                         Fairfield Manufacturing    2 years
1651629                           The Dartmouth Company   < 1 year
1651630                                             FDA  10+ years
1651631                       Norman G. Olson Insurance    6 years
1651632                        Panavision International     1 year
1651633                                   Self-Employed   < 1 year
1651634                                 Stratagem, Inc.     1 year
1651635                           ISO MERCHANT SERVICES    9 years
1651636                            Auto motors of miami    6 years
1651637                             Eastland Park Hotel   < 1 year
1651638                                  Zensah Company    3 years
1651639                             Turner Construction     1 year
1651640                                Ping Interactive     1 year
1651641                            UNIQUE ID WEB DESIGN   < 1 year
1651642                              Oracle Corporation    8 years
1651643                                  MetraTech Corp    7 years
1651644  Institute for Mind/Body Research and Education    2 years
1651645                            RoadNarrows Robotics   < 1 year
1651646                                      Viget Labs     1 year
1651647                 Northwestern School Corporation    4 years
1651648                                            <NA>   < 1 year
1651649                           Peerless Pump Company    7 years
1651650                                   Self-employed     1 year
1651651                                          Oracle    2 years
1651652                                            <NA>   < 1 year
1651653                                       MetraTech    8 years
1651654                                            <NA>   < 1 year
1651655                              Stark and Roth Inc    2 years
1651656                                 Millenium Group    4 years
1651657                                  Self-Employeed   < 1 year
1651658                               Rush Univ Med Grp     1 year
1651659                             A. F. Wolfers, Inc.    5 years
1651660                                 FiSite Research    4 years
1651661                      Squarewave Solutions, Ltd.    3 years
1651662                                            <NA>   < 1 year
1651663                                            <NA>   < 1 year
1651664                                Evergreen Center   < 1 year
1654271                                Freedom Mortgage     1 year
1654312                                            <NA>   < 1 year
1654326                                   self-employed  10+ years
1654331                                  Private family    5 years
1654332                                   H. Beck, Inc.    2 years
1654333                               PEER Center, Inc.    5 years
1654334                                  Douglas County    6 years
1654335                          Perelly transport, inc    3 years
1654336                             Sale solutions, inc    2 years
1654337                                Cicero Solutions   < 1 year
1654338                         Meyers Associates, L.P.   < 1 year
1654340                                Costco wholesale     1 year
1654341                                  MBA Team, Inc.     1 year
1654342                     miami international freight    2 years
1654343                                    vg-tech, inc    3 years
1654344                            UWF Parking Services   < 1 year
1654345                     Securitas Security Services    8 years
1654346                               Packard Transport   < 1 year
1654347               Robert Wood Johnson/ Saint Peters     1 year
1654348    INSTTITUTE FOR CHILD AND FAMILY HEALTH, INC.     1 year
1654349                             Publix Supermarkets  10+ years
1654350                                        HSBC USA   < 1 year
1654351                    New England Quality Electric    3 years

,Total (Null/Total),Percentage (%),Data Type
id,0/1379449,0.000000,string[pyarrow]
member_id,1379449/1379449,100.000000,null[pyarrow]
loan_amnt,0/1379449,0.000000,double[pyarrow]
funded_amnt,0/1379449,0.000000,double[pyarrow]
funded_amnt_inv,0/1379449,0.000000,double[pyarrow]
term,0/1379449,0.000000,string[pyarrow]
int_rate,0/1379449,0.000000,double[pyarrow]
installment,0/1379449,0.000000,double[pyarrow]
grade,0/1379449,0.000000,string[pyarrow]
sub_grade,0/1379449,0.000000,string[pyarrow]
emp_title,88965/1379449,6.449314,string[pyarrow]
emp_length,81394/1379449,5.900472,string[pyarrow]
home_ownership,0/1379449,0.000000,string[pyarrow]
annual_inc,0/1379449,0.000000,double[pyarrow]
verification_status,0/1379449,0.000000,string[pyarrow]
issue_d,0/1379449,0.000000,string[pyarrow]
loan_status,0/1379449,0.000000,string[pyarrow]
pymnt_plan,0/1379449,0.000000,string[pyarrow]
url,0/1379449,0.000000,string[pyarrow]
desc,1255956/1379449,91.047657,string[pyarrow]
purpose,0/1379449,0.000000,string[pyarrow]
title,17113/1379449,1.240568,string[pyarrow]
zip_code,0/1379449,0.000000,string[pyarrow]
addr_state,0/1379449,0.000000,string[pyarrow]
dti,412/1379449,0.029867,double[pyarrow]
delinq_2yrs,0/1379449,0.000000,double[pyarrow]
earliest_cr_line,0/1379449,0.000000,string[pyarrow]
fico_range_low,0/1379449,0.000000,double[pyarrow]
fico_range_high,0/1379449,0.000000,double[pyarrow]
inq_last_6mths,0/1379449,0.000000,double[pyarrow]
mths_since_last_delinq,694607/1379449,50.353946,double[pyarrow]
mths_since_last_record,1144762/1379449,82.986903,double[pyarrow]
open_acc,0/1379449,0.000000,double[pyarrow]
pub_rec,0/1379449,0.000000,double[pyarrow]
revol_bal,0/1379449,0.000000,double[pyarrow]
revol_util,895/1379449,0.064881,double[pyarrow]
total_acc,0/1379449,0.000000,double[pyarrow]
initial_list_status,0/1379449,0.000000,string[pyarrow]
out_prncp,0/1379449,0.000000,double[pyarrow]
out_prncp_inv,0/1379449,0.000000,double[pyarrow]
total_pymnt,0/1379449,0.000000,double[pyarrow]
total_pymnt_inv,0/1379449,0.000000,double[pyarrow]
total_rec_prncp,0/1379449,0.000000,double[pyarrow]
total_rec_int,0/1379449,0.000000,double[pyarrow]
total_rec_late_fee,0/1379449,0.000000,double[pyarrow]
recoveries,0/1379449,0.000000,double[pyarrow]
collection_recovery_fee,0/1379449,0.000000,double[pyarrow]
last_pymnt_d,2415/1379449,0.175070,string[pyarrow]
last_pymnt_amnt,0/1379449,0.000000,double[pyarrow]
next_pymnt_d,1345197/1379449,97.516980,string[pyarrow]
last_credit_pull_d,0/1379449,0.000000,string[pyarrow]
last_fico_range_high,0/1379449,0.000000,double[pyarrow]
last_fico_range_low,0/1379449,0.000000,double[pyarrow]
collections_12_mths_ex_med,0/1379449,0.000000,double[pyarrow]
mths_since_last_major_derog,1015296/1379449,73.601561,double[pyarrow]
policy_code,0/1379449,0.000000,double[pyarrow]
application_type,0/1379449,0.000000,string[pyarrow]
annual_inc_joint,1349872/1379449,97.855883,double[pyarrow]
dti_joint,1349875/1379449,97.856101,double[pyarrow]
verification_status_joint,1350128/1379449,97.874441,string[pyarrow]
acc_now_delinq,0/1379449,0.000000,double[pyarrow]
tot_coll_amt,67469/1379449,4.891011,double[pyarrow]
tot_cur_bal,67469/1379449,4.891011,double[pyarrow]
open_acc_6m,810305/1379449,58.741208,double[pyarrow]
open_act_il,810305/1379449,58.741208,double[pyarrow]
open_il_12m,810305/1379449,58.741208,double[pyarrow]
open_il_24m,810305/1379449,58.741208,double[pyarrow]
mths_since_rcnt_il,825654/1379449,59.853898,double[pyarrow]
total_bal_il,810305/1379449,58.741208,double[pyarrow]
il_util,887539/1379449,64.340110,double[pyarrow]
open_rv_12m,810305/1379449,58.741208,double[pyarrow]
open_rv_24m,810305/1379449,58.741208,double[pyarrow]
max_bal_bc,810305/1379449,58.741208,double[pyarrow]
all_util,810364/1379449,58.745485,double[pyarrow]
total_rev_hi_lim,67469/1379449,4.891011,double[pyarrow]
inq_fi,810305/1379449,58.741208,double[pyarrow]
total_cu_tl,810305/1379449,58.741208,double[pyarrow]
inq_last_12m,810305/1379449,58.741208,double[pyarrow]
acc_open_past_24mths,47223/1379449,3.423323,double[pyarrow]
avg_cur_bal,67492/1379449,4.892678,double[pyarrow]
bc_open_to_buy,61562/1379449,4.462796,double[pyarrow]
bc_util,62352/1379449,4.520066,double[pyarrow]
chargeoff_within_12_mths,0/1379449,0.000000,double[pyarrow]
delinq_amnt,0/1379449,0.000000,double[pyarrow]
mo_sin_old_il_acct,106703/1379449,7.735190,double[pyarrow]
mo_sin_old_rev_tl_op,67470/1379449,4.891083,double[pyarrow]
mo_sin_rcnt_rev_tl_op,67470/1379449,4.891083,double[pyarrow]
mo_sin_rcnt_tl,67469/1379449,4.891011,double[pyarrow]
mort_acc,47223/1379449,3.423323,double[pyarrow]
mths_since_recent_bc,60603/1379449,4.393276,double[pyarrow]
mths_since_recent_bc_dlq,1051638/1379449,76.236091,double[pyarrow]
mths_since_recent_inq,176950/1379449,12.827586,double[pyarrow]
mths_since_recent_revol_delinq,917077/1379449,66.481399,double[pyarrow]
num_accts_ever_120_pd,67469/1379449,4.891011,double[pyarrow]
num_actv_bc_tl,67469/1379449,4.891011,double[pyarrow]
num_actv_rev_tl,67469/1379449,4.891011,double[pyarrow]
num_bc_sats,55783/1379449,4.043861,double[pyarrow]
num_bc_tl,67469/1379449,4.891011,double[pyarrow]
num_il_tl,67469/1379449,4.891011,double[pyarrow]
num_op_rev_tl,67469/1379449,4.891011,double[pyarrow]
num_rev_accts,67470/1379449,4.891083,double[pyarrow]
num_rev_tl_bal_gt_0,67469/1379449,4.891011,double[pyarrow]
num_sats,55783/1379449,4.043861,double[pyarrow]
num_tl_120dpd_2m,119396/1379449,8.655340,double[pyarrow]
num_tl_30dpd,67469/1379449,4.891011,double[pyarrow]
num_tl_90g_dpd_24m,67469/1379449,4.891011,double[pyarrow]
num_tl_op_past_12m,67469/1379449,4.891011,double[pyarrow]
pct_tl_nvr_dlq,67622/1379449,4.902102,double[pyarrow]
percent_bc_gt_75,61976/1379449,4.492808,double[pyarrow]
pub_rec_bankruptcies,642/1379449,0.046540,double[pyarrow]
tax_liens,0/1379449,0.000000,double[pyarrow]
tot_hi_cred_lim,67469/1379449,4.891011,double[pyarrow]
total_bal_ex_mort,47223/1379449,3.423323,double[pyarrow]
total_bc_limit,47223/1379449,3.423323,double[pyarrow]
total_il_high_credit_limit,67469/1379449,4.891011,double[pyarrow]
revol_bal_joint,1357365/1379449,98.399071,double[pyarrow]
sec_app_fico_range_low,1357364/1379449,98.398998,double[pyarrow]
sec_app_fico_range_high,1357364/1379449,98.398998,double[pyarrow]
sec_app_earliest_cr_line,1357364/1379449,98.398998,string[pyarrow]
sec_app_inq_last_6mths,1357364/1379449,98.398998,double[pyarrow]
sec_app_mort_acc,1357364/1379449,98.398998,double[pyarrow]
sec_app_open_acc,1357364/1379449,98.398998,double[pyarrow]
sec_app_revol_util,1357759/1379449,98.427633,double[pyarrow]
sec_app_open_act_il,1357364/1379449,98.398998,double[pyarrow]
sec_app_num_rev_accts,1357364/1379449,98.398998,double[pyarrow]
sec_app_chargeoff_within_12_mths,1357364/1379449,98.398998,double[pyarrow]
sec_app_collections_12_mths_ex_med,1357364/1379449,98.398998,double[pyarrow]
sec_app_mths_since_last_major_derog,1371350/1379449,99.412882,double[pyarrow]
hardship_flag,0/1379449,0.000000,string[pyarrow]
hardship_type,1371447/1379449,99.419913,string[pyarrow]
hardship_reason,1371447/1379449,99.419913,string[pyarrow]
hardship_status,1371447/1379449,99.419913,string[pyarrow]
deferral_term,1371447/1379449,99.419913,double[pyarrow]
hardship_amount,1371447/1379449,99.419913,double[pyarrow]
hardship_start_date,1371447/1379449,99.419913,string[pyarrow]
hardship_end_date,1371447/1379449,99.419913,string[pyarrow]
payment_plan_start_date,1371447/1379449,99.419913,string[pyarrow]
hardship_length,1371447/1379449,99.419913,double[pyarrow]
hardship_dpd,1371447/1379449,99.419913,double[pyarrow]
hardship_loan_status,1371447/1379449,99.419913,string[pyarrow]
orig_projected_additional_accrued_interest,1373632/1379449,99.578310,double[pyarrow]
hardship_payoff_balance_amount,1371447/1379449,99.419913,double[pyarrow]
hardship_last_payment_amount,1371447/1379449,99.419913,double[pyarrow]
disbursement_method,0/1379449,0.000000,string[pyarrow]
debt_settlement_flag,0/1379449,0.000000,string[pyarrow]
debt_settlement_flag_date,1345247/1379449,97.520604,string[pyarrow]
settlement_status,1345247/1379449,97.520604,string[pyarrow]
settlement_date,1345247/1379449,97.520604,string[pyarrow]
settlement_amount,1345247/1379449,97.520604,double[pyarrow]
settlement_percentage,1345247/1379449,97.520604,double[pyarrow]
settlement_term,1345247/1379449,97.520604,double[pyarrow]

Modify Columns:

In [5]:
# id: Change Data Type to Integer
df['id'] = df['id'].astype('int64[pyarrow]')

# member_id: Delete because it is empty
df = df.drop(columns=["member_id"])

# loan_amnt: Change Data Type to Integer
df['loan_amnt'] = df['loan_amnt'].astype('int64[pyarrow]')

# funded_amnt: Delete because it is the same as/extremely similar to loan_amnt
df = df.drop(columns=["funded_amnt"])

# funded_amnt: Delete because it is the same as/extremely similar to loan_amnt
df = df.drop(columns=["funded_amnt_inv"])

# term: Transform values to 0s and 1s and Change Data Type to Bool
df['term'] = df['term'].map({" 36 months": 0, " 60 months": 1})
df['term'] = df['term'].astype('bool[pyarrow]')

# int_rate: Not Modified
# installment: Not Modified

# grade: Delete because it is the same as/extremely similar to sub_grade
df = df.drop(columns=["grade"])

# sub_grade: Transform values to Integers and Change Data Type to Integer
df['sub_grade'] = df['sub_grade'].map({'A1': 0, 'A2': 1, 'A3': 2, 'A4': 3, 'A5': 4, 'B1': 5, 'B2': 6, 'B3': 7, 'B4': 8, 'B5': 9, 'C1': 10, 'C2': 11, 'C3': 12, 'C4': 13, 'C5': 14, 'D1': 15, 'D2': 16, 'D3': 17, 'D4': 18, 'D5': 19, 'E1': 20, 'E2': 21, 'E3': 22, 'E4': 23, 'E5': 24, 'F1': 25, 'F2': 26, 'F3': 27, 'F4': 28, 'F5': 29, 'G1': 30, 'G2': 31, 'G3': 32, 'G4': 33, 'G5': 34})
df['sub_grade'] = df['sub_grade'].astype('int64[pyarrow]')

# emp_title: Delete because it is not usable
df = df.drop(columns=["emp_title"])

# emp_length: Transform values to Integers and Change Data Type to Integer
df['emp_length'] = df['emp_length'].map({'< 1 year': 0, '1 year': 1, '2 years': 2, '3 years': 3, '4 years': 4, '5 years': 5, '6 years': 6, '7 years': 7, '8 years': 8, '9 years': 9, '10+ years': 10})
df['emp_length'] = df['emp_length'].astype('int64[pyarrow]')

# home_ownership: Transform values to Integers and Change Data Type to Integer
df['home_ownership'] = df['home_ownership'].map({'ANY': 0, 'NONE': 0, 'OTHER': 0, 'RENT': 1, 'MORTGAGE': 2, 'OWN': 3})
df['home_ownership'] = df['home_ownership'].astype('int64[pyarrow]')

# annual_inc: Not Modified

# verification_status: Delete because it is not usable
df = df.drop(columns=["verification_status"])

# sub_grade: Transform values to Date and Change Data Type to Date
df['issue_d'] = pd.to_datetime(df['issue_d'], format='%b-%Y')
df['issue_d'] = df['issue_d'].astype('date32[pyarrow]')

# loan_status: Transform values to Integers and Change Data Type to Integer
df['loan_status'] = df['loan_status'].map({'Fully Paid': '0', 'In Grace Period': '1', 'Late (16-30 days)': '2', 'Late (31-120 days)': '3', 'Charged Off': '4'})
df['loan_status'] = df['loan_status'].astype('int64[pyarrow]')

# pymnt_plan: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["pymnt_plan"])

# url: Delete because it is not usable
df = df.drop(columns=["url"])

# desc: Delete because it is not usable
df = df.drop(columns=["desc"])

# purpose: Transform values to Integers and Change Data Type to Integer
df['purpose'] = df['purpose'].map({'car': '0', 'credit_card': '1', 'debt_consolidation': '2', 'educational': '3', 'home_improvement': '4', 'house': '5', 'major_purchase': '6', 'medical': '7', 'moving': '8', 'other': '9', 'renewable_energy': '10', 'small_business': '11', 'vacation': '12', 'wedding': '13'})
df['purpose'] = df['purpose'].astype('int64[pyarrow]')

# title: Delete because it is the same as/extremely similar to purpose
df = df.drop(columns=["title"])

# zip_code: Delete because it is the same as/extremely similar to addr_state
df = df.drop(columns=["zip_code"])

# addr_state: Transform values to Integers and Change Data Type to Integer
df['addr_state'] = df['addr_state'].map({'AK': '0', 'AL': '1', 'AR': '2', 'AZ': '3', 'CA': '4', 'CO': '5', 'CT': '6', 'DC': '7', 'DE': '8', 'FL': '9', 'GA': '10', 'HI': '11', 'IA': '12', 'ID': '13', 'IL': '14', 'IN': '15', 'KS': '16', 'KY': '17', 'LA': '18', 'MA': '19', 'MD': '20', 'ME': '21', 'MI': '22', 'MN': '23', 'MO': '24', 'MS': '25', 'MT': '26', 'NC': '27', 'ND': '28', 'NE': '29', 'NH': '30', 'NJ': '31', 'NM': '32', 'NV': '33', 'NY': '34', 'OH': '35', 'OK': '36', 'OR': '37', 'PA': '38', 'RI': '39', 'SC': '40', 'SD': '41', 'TN': '42', 'TX': '43', 'UT': '44', 'VA': '45', 'VT': '46', 'WA': '47', 'WI': '48', 'WV': '49', 'WY': '50'})
df['purpose'] = df['purpose'].astype('int64[pyarrow]')

# dti: Not Modified

# delinq_2yrs: Change Data Type to Integer
df['delinq_2yrs'] = df['delinq_2yrs'].astype('int64[pyarrow]')

# earliest_cr_line: Transform values to Date and Change Data Type to Date
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%Y')
df['earliest_cr_line'] = df['earliest_cr_line'].astype('date32[pyarrow]')

# fico_range_low: Change Data Type to Integer
df['fico_range_low'] = df['fico_range_low'].astype('int64[pyarrow]')

# fico_range_high: Delete because it is the same as/extremely similar to fico_range_low
df = df.drop(columns=["fico_range_high"])

# fico_range_low: Change Data Type to Integer
df['fico_range_low'] = df['fico_range_low'].astype('int64[pyarrow]')

# inq_last_6mths: Change Data Type to Integer
df['inq_last_6mths'] = df['inq_last_6mths'].astype('int64[pyarrow]')

# mths_since_last_delinq: Change Data Type to Integer
df['mths_since_last_delinq'] = df['mths_since_last_delinq'].astype('int64[pyarrow]')

# mths_since_last_record: Change Data Type to Integer
df['mths_since_last_record'] = df['mths_since_last_record'].astype('int64[pyarrow]')

# open_acc: Change Data Type to Integer
df['open_acc'] = df['open_acc'].astype('int64[pyarrow]')

# pub_rec: Change Data Type to Integer
df['pub_rec'] = df['pub_rec'].astype('int64[pyarrow]')

# revol_bal: Not Modified
# revol_util: Not Modified
# total_acc: Not Modified

# initial_list_status: Transform values to 0s and 1s and Change Data Type to Bool
df['initial_list_status'] = df['initial_list_status'].map({"w": 0, "f": 1})
df['initial_list_status'] = df['initial_list_status'].astype('bool[pyarrow]')

# out_prncp: Delete because it is not usable
df = df.drop(columns=["out_prncp"])

# out_prncp_inv: Delete because it is not usable
df = df.drop(columns=["out_prncp_inv"])

# total_pymnt: Delete because it is not usable
df = df.drop(columns=["total_pymnt"])

# total_pymnt_inv: Delete because it is not usable
df = df.drop(columns=["total_pymnt_inv"])

# total_rec_prncp: Delete because it is not usable
df = df.drop(columns=["total_rec_prncp"])

# total_rec_int: Delete because it is not usable
df = df.drop(columns=["total_rec_int"])

# total_rec_late_fee: Delete because it is not usable
df = df.drop(columns=["total_rec_late_fee"])

# recoveries: Delete because it is not usable
df = df.drop(columns=["recoveries"])

# collection_recovery_fee: Delete because it is not usable
df = df.drop(columns=["collection_recovery_fee"])

# last_pymnt_d: Delete because it is not usable
df = df.drop(columns=["last_pymnt_d"])

# last_pymnt_amnt: Delete because it is not usable
df = df.drop(columns=["last_pymnt_amnt"])

# next_pymnt_d: Delete because it is not usable
df = df.drop(columns=["next_pymnt_d"])

# last_credit_pull_d: Delete because it is not usable
df = df.drop(columns=["last_credit_pull_d"])

# last_fico_range_high: Delete because it is not usable
df = df.drop(columns=["last_fico_range_high"])

# last_fico_range_low: Delete because it is not usable
df = df.drop(columns=["last_fico_range_low"])

# collections_12_mths_ex_med: Delete because it is not usable
df = df.drop(columns=["collections_12_mths_ex_med"])

# mths_since_last_major_derog: Change Data Type to Integer
df['mths_since_last_major_derog'] = df['mths_since_last_major_derog'].astype('int64[pyarrow]')

# policy_code: Delete because it is not usable
df = df.drop(columns=["policy_code"])

# application_type: Transform values to 0s and 1s and Change Data Type to Bool
df['application_type'] = df['application_type'].map({'Individual': '0', 'Joint App': '1'})
df['application_type'] = df['application_type'].astype('bool[pyarrow]')

# annual_inc_joint: Delete because it is not usable
df = df.drop(columns=["annual_inc_joint"])

# dti_joint: Delete because it is not usable
df = df.drop(columns=["dti_joint"])

# verification_status_joint: Delete because it is not usable
df = df.drop(columns=["verification_status_joint"])

# acc_now_delinq: Change Data Type to Integer
df['acc_now_delinq'] = df['acc_now_delinq'].astype('int64[pyarrow]')

# tot_coll_amt: Not Modified
# tot_cur_bal: Not Modified

# open_acc_6m: Delete because it is the same as/extremely similar to acc_open_past_24mths
df = df.drop(columns=["open_acc_6m"])

# open_act_il: Change Data Type to Integer
df['open_act_il'] = df['open_act_il'].astype('int64[pyarrow]')

# open_il_12m: Delete because it is the same as/extremely similar to open_act_il
df = df.drop(columns=["open_il_12m"])

# open_il_24m: Delete because it is the same as/extremely similar to open_act_il
df = df.drop(columns=["open_il_24m"])

# mths_since_rcnt_il: Delete because it is the same as/extremely similar to open_act_il
df = df.drop(columns=["mths_since_rcnt_il"])

# total_bal_il: Delete because it is the same as/extremely similar to il_util
df = df.drop(columns=["total_bal_il"])

# il_util: Not Modified

# open_rv_12m: Delete because it is the same as/extremely similar to open_rv_24m
df = df.drop(columns=["open_rv_12m"])

# open_rv_24m: Change Data Type to Integer
df['open_rv_24m'] = df['open_rv_24m'].astype('int64[pyarrow]')

# max_bal_bc: Not Modified
# all_util: Not Modified
# total_rev_hi_lim: Not Modified

# inq_fi: Change Data Type to Integer
df['inq_fi'] = df['inq_fi'].astype('int64[pyarrow]')

# total_cu_tl: Change Data Type to Integer
df['total_cu_tl'] = df['total_cu_tl'].astype('int64[pyarrow]')

# inq_last_12m: Delete because it is the same as/extremely similar to inq_last_6mths
df = df.drop(columns=["inq_last_12m"])

# avg_cur_bal: Delete because it is the same as/extremely similar to tot_cur_bal
df = df.drop(columns=["avg_cur_bal"])

# bc_open_to_buy: Not Modified
# bc_util: Not Modified

# chargeoff_within_12_mths: Change Data Type to Integer
df['chargeoff_within_12_mths'] = df['chargeoff_within_12_mths'].astype('int64[pyarrow]')

# delinq_amnt: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["delinq_amnt"])

# mo_sin_old_il_acct: Change Data Type to Integer
df['mo_sin_old_il_acct'] = df['mo_sin_old_il_acct'].astype('int64[pyarrow]')

# mo_sin_old_rev_tl_op: Change Data Type to Integer
df['mo_sin_old_rev_tl_op'] = df['mo_sin_old_rev_tl_op'].astype('int64[pyarrow]')

# mo_sin_rcnt_rev_tl_op: Change Data Type to Integer
df['mo_sin_rcnt_rev_tl_op'] = df['mo_sin_rcnt_rev_tl_op'].astype('int64[pyarrow]')

# mo_sin_rcnt_tl: Change Data Type to Integer
df['mo_sin_rcnt_tl'] = df['mo_sin_rcnt_tl'].astype('int64[pyarrow]')

# mort_acc: Change Data Type to Integer
df['mort_acc'] = df['mort_acc'].astype('int64[pyarrow]')

# mths_since_recent_bc: Change Data Type to Integer
df['mths_since_recent_bc'] = df['mths_since_recent_bc'].astype('int64[pyarrow]')

# mths_since_recent_bc_dlq: Change Data Type to Integer
df['mths_since_recent_bc_dlq'] = df['mths_since_recent_bc_dlq'].astype('int64[pyarrow]')

# mths_since_recent_inq: Change Data Type to Integer
df['mths_since_recent_inq'] = df['mths_since_recent_inq'].astype('int64[pyarrow]')

# mths_since_recent_revol_delinq: Change Data Type to Integer
df['mths_since_recent_revol_delinq'] = df['mths_since_recent_revol_delinq'].astype('int64[pyarrow]')

# num_accts_ever_120_pd: Change Data Type to Integer
df['num_accts_ever_120_pd'] = df['num_accts_ever_120_pd'].astype('int64[pyarrow]')

# num_actv_bc_tl: Change Data Type to Integer
df['num_actv_bc_tl'] = df['num_actv_bc_tl'].astype('int64[pyarrow]')

# num_actv_rev_tl: Change Data Type to Integer
df['num_actv_rev_tl'] = df['num_actv_rev_tl'].astype('int64[pyarrow]')

# num_bc_sats: Change Data Type to Integer
df['num_bc_sats'] = df['num_bc_sats'].astype('int64[pyarrow]')

# num_bc_tl: Change Data Type to Integer
df['num_bc_tl'] = df['num_bc_tl'].astype('int64[pyarrow]')

# num_il_tl: Change Data Type to Integer
df['num_il_tl'] = df['num_il_tl'].astype('int64[pyarrow]')

# num_op_rev_tl: Change Data Type to Integer
df['num_op_rev_tl'] = df['num_op_rev_tl'].astype('int64[pyarrow]')

# num_rev_accts: Change Data Type to Integer
df['num_rev_accts'] = df['num_rev_accts'].astype('int64[pyarrow]')

# num_rev_tl_bal_gt_0: Change Data Type to Integer
df['num_rev_tl_bal_gt_0'] = df['num_rev_tl_bal_gt_0'].astype('int64[pyarrow]')

# num_sats: Change Data Type to Integer
df['num_sats'] = df['num_sats'].astype('int64[pyarrow]')

# num_tl_120dpd_2m: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["num_tl_120dpd_2m"])

# num_tl_30dpd: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["num_tl_30dpd"])

# num_tl_90g_dpd_24m: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["num_tl_90g_dpd_24m"])

# num_tl_op_past_12m: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["num_tl_op_past_12m"])

# pct_tl_nvr_dlq: Not Modified
# percent_bc_gt_75: Not Modified

# pub_rec_bankruptcies: Change Data Type to Integer
df['pub_rec_bankruptcies'] = df['pub_rec_bankruptcies'].astype('int64[pyarrow]')

# tax_liens: Change Data Type to Integer
df['tax_liens'] = df['tax_liens'].astype('int64[pyarrow]')

# tot_hi_cred_lim: Not Modified
# total_bal_ex_mort: Not Modified
# total_bc_limit: Not Modified
# total_il_high_credit_limit: Not Modified

# revol_bal_joint: Delete because it is not usable
df = df.drop(columns=["revol_bal_joint"])

# sec_app_fico_range_low: Delete because it is not usable
df = df.drop(columns=["sec_app_fico_range_low"])

# sec_app_fico_range_high: Delete because it is not usable
df = df.drop(columns=["sec_app_fico_range_high"])

# sec_app_earliest_cr_line: Delete because it is not usable
df = df.drop(columns=["sec_app_earliest_cr_line"])

# sec_app_inq_last_6mths: Delete because it is not usable
df = df.drop(columns=["sec_app_inq_last_6mths"])

# sec_app_mort_acc: Delete because it is not usable
df = df.drop(columns=["sec_app_mort_acc"])

# sec_app_open_acc: Delete because it is not usable
df = df.drop(columns=["sec_app_open_acc"])

# sec_app_revol_util: Delete because it is not usable
df = df.drop(columns=["sec_app_revol_util"])

# sec_app_open_act_il: Delete because it is not usable
df = df.drop(columns=["sec_app_open_act_il"])

# sec_app_num_rev_accts: Delete because it is not usable
df = df.drop(columns=["sec_app_num_rev_accts"])

# sec_app_chargeoff_within_12_mths: Delete because it is not usable
df = df.drop(columns=["sec_app_chargeoff_within_12_mths"])

# sec_app_collections_12_mths_ex_med: Delete because it is not usable
df = df.drop(columns=["sec_app_collections_12_mths_ex_med"])

# sec_app_mths_since_last_major_derog: Delete because it is not usable
df = df.drop(columns=["sec_app_mths_since_last_major_derog"])

# hardship_flag: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["hardship_flag"])

# hardship_type: Delete because it is not usable
df = df.drop(columns=["hardship_type"])

# hardship_reason: Delete because it is not usable
df = df.drop(columns=["hardship_reason"])

# hardship_status: Delete because it is not usable
df = df.drop(columns=["hardship_status"])

# deferral_term: Delete because it is not usable
df = df.drop(columns=["deferral_term"])

# hardship_amount: Delete because it is not usable
df = df.drop(columns=["hardship_amount"])

# hardship_start_date: Delete because it is not usable
df = df.drop(columns=["hardship_start_date"])

# hardship_end_date: Delete because it is not usable
df = df.drop(columns=["hardship_end_date"])

# payment_plan_start_date: Delete because it is not usable
df = df.drop(columns=["payment_plan_start_date"])

# hardship_length: Delete because it is not usable
df = df.drop(columns=["hardship_length"])

# hardship_dpd: Delete because it is not usable
df = df.drop(columns=["hardship_dpd"])

# hardship_loan_status: Delete because it is not usable
df = df.drop(columns=["hardship_loan_status"])

# orig_projected_additional_accrued_interest: Delete because it is not usable
df = df.drop(columns=["orig_projected_additional_accrued_interest"])

# hardship_payoff_balance_amount: Delete because it is not usable
df = df.drop(columns=["hardship_payoff_balance_amount"])

# hardship_last_payment_amount: Delete because it is not usable
df = df.drop(columns=["hardship_last_payment_amount"])

# disbursement_method: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["disbursement_method"])

# debt_settlement_flag: Delete because of Data Leakage as it is future information that would give the model certainty in predictions
df = df.drop(columns=["debt_settlement_flag"])

# debt_settlement_flag_date: Delete because it is not usable
df = df.drop(columns=["debt_settlement_flag_date"])

# settlement_status: Delete because it is not usable
df = df.drop(columns=["settlement_status"])

# settlement_date: Delete because it is not usable
df = df.drop(columns=["settlement_date"])

# settlement_amount: Delete because it is not usable
df = df.drop(columns=["settlement_amount"])

# settlement_percentage: Delete because it is not usable
df = df.drop(columns=["settlement_percentage"])

# settlement_term: Delete because it is not usable
df = df.drop(columns=["settlement_term"])

print_column_info(df)
df.head()

,Total (Null/Total),Percentage (%),Data Type
id,0/1379449,0.000000,int64[pyarrow]
loan_amnt,0/1379449,0.000000,int64[pyarrow]
term,0/1379449,0.000000,bool[pyarrow]
int_rate,0/1379449,0.000000,double[pyarrow]
installment,0/1379449,0.000000,double[pyarrow]
sub_grade,0/1379449,0.000000,int64[pyarrow]
emp_length,81394/1379449,5.900472,int64[pyarrow]
home_ownership,0/1379449,0.000000,int64[pyarrow]
annual_inc,0/1379449,0.000000,double[pyarrow]
issue_d,0/1379449,0.000000,date32[day][pyarrow]
loan_status,0/1379449,0.000000,int64[pyarrow]
purpose,0/1379449,0.000000,int64[pyarrow]
addr_state,0/1379449,0.000000,object
dti,412/1379449,0.029867,double[pyarrow]
delinq_2yrs,0/1379449,0.000000,int64[pyarrow]
earliest_cr_line,0/1379449,0.000000,date32[day][pyarrow]
fico_range_low,0/1379449,0.000000,int64[pyarrow]
inq_last_6mths,0/1379449,0.000000,int64[pyarrow]
mths_since_last_delinq,694607/1379449,50.353946,int64[pyarrow]
mths_since_last_record,1144762/1379449,82.986903,int64[pyarrow]
open_acc,0/1379449,0.000000,int64[pyarrow]
pub_rec,0/1379449,0.000000,int64[pyarrow]
revol_bal,0/1379449,0.000000,double[pyarrow]
revol_util,895/1379449,0.064881,double[pyarrow]
total_acc,0/1379449,0.000000,double[pyarrow]
initial_list_status,0/1379449,0.000000,bool[pyarrow]
mths_since_last_major_derog,1015296/1379449,73.601561,int64[pyarrow]
application_type,0/1379449,0.000000,bool[pyarrow]
acc_now_delinq,0/1379449,0.000000,int64[pyarrow]
tot_coll_amt,67469/1379449,4.891011,double[pyarrow]
tot_cur_bal,67469/1379449,4.891011,double[pyarrow]
open_act_il,810305/1379449,58.741208,int64[pyarrow]
il_util,887539/1379449,64.340110,double[pyarrow]
open_rv_24m,810305/1379449,58.741208,int64[pyarrow]
max_bal_bc,810305/1379449,58.741208,double[pyarrow]
all_util,810364/1379449,58.745485,double[pyarrow]
total_rev_hi_lim,67469/1379449,4.891011,double[pyarrow]
inq_fi,810305/1379449,58.741208,int64[pyarrow]
total_cu_tl,810305/1379449,58.741208,int64[pyarrow]
acc_open_past_24mths,47223/1379449,3.423323,double[pyarrow]
bc_open_to_buy,61562/1379449,4.462796,double[pyarrow]
bc_util,62352/1379449,4.520066,double[pyarrow]
chargeoff_within_12_mths,0/1379449,0.000000,int64[pyarrow]
mo_sin_old_il_acct,106703/1379449,7.735190,int64[pyarrow]
mo_sin_old_rev_tl_op,67470/1379449,4.891083,int64[pyarrow]
mo_sin_rcnt_rev_tl_op,67470/1379449,4.891083,int64[pyarrow]
mo_sin_rcnt_tl,67469/1379449,4.891011,int64[pyarrow]
mort_acc,47223/1379449,3.423323,int64[pyarrow]
mths_since_recent_bc,60603/1379449,4.393276,int64[pyarrow]
mths_since_recent_bc_dlq,1051638/1379449,76.236091,int64[pyarrow]
mths_since_recent_inq,176950/1379449,12.827586,int64[pyarrow]
mths_since_recent_revol_delinq,917077/1379449,66.481399,int64[pyarrow]
num_accts_ever_120_pd,67469/1379449,4.891011,int64[pyarrow]
num_actv_bc_tl,67469/1379449,4.891011,int64[pyarrow]
num_actv_rev_tl,67469/1379449,4.891011,int64[pyarrow]
num_bc_sats,55783/1379449,4.043861,int64[pyarrow]
num_bc_tl,67469/1379449,4.891011,int64[pyarrow]
num_il_tl,67469/1379449,4.891011,int64[pyarrow]
num_op_rev_tl,67469/1379449,4.891011,int64[pyarrow]
num_rev_accts,67470/1379449,4.891083,int64[pyarrow]
num_rev_tl_bal_gt_0,67469/1379449,4.891011,int64[pyarrow]
num_sats,55783/1379449,4.043861,int64[pyarrow]
pct_tl_nvr_dlq,67622/1379449,4.902102,double[pyarrow]
percent_bc_gt_75,61976/1379449,4.492808,double[pyarrow]
pub_rec_bankruptcies,642/1379449,0.046540,int64[pyarrow]
tax_liens,0/1379449,0.000000,int64[pyarrow]
tot_hi_cred_lim,67469/1379449,4.891011,double[pyarrow]
total_bal_ex_mort,47223/1379449,3.423323,double[pyarrow]
total_bc_limit,47223/1379449,3.423323,double[pyarrow]
total_il_high_credit_limit,67469/1379449,4.891011,double[pyarrow]

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,issue_d,loan_status,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,mths_since_last_major_derog,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_act_il,il_util,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,acc_open_past_24mths,bc_open_to_buy,bc_util,chargeoff_within_12_mths,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68407277,3600,False,13.99,123.03,13,10,2,55000.0,2015-12-01,0,2,38,5.91,0,2003-08-01,675,1,30,<NA>,7,0,2765.0,29.7,13.0,False,30,False,0,722.0,144904.0,2,36.0,3,722.0,34.0,9300.0,3,1,4.0,1506.0,37.2,0,148,128,3,3,1,4,69,4,69,2,2,4,2,5,3,4,9,4,7,76.9,0.0,0,0,178050.0,7746.0,2400.0,13734.0
1,68355089,24700,False,11.99,820.28,10,10,2,65000.0,2015-12-01,0,11,41,16.06,1,1999-12-01,715,4,6,<NA>,22,0,21470.0,19.2,38.0,False,<NA>,False,0,0.0,204396.0,1,73.0,3,6472.0,29.0,111800.0,0,0,4.0,57830.0,27.1,0,113,192,2,2,4,2,<NA>,0,6,0,5,5,13,17,6,20,27,5,22,97.4,7.7,0,0,314017.0,39475.0,79300.0,24667.0
2,68341763,20000,True,10.78,432.66,8,10,2,63000.0,2015-12-01,0,4,14,10.78,0,2000-08-01,695,0,<NA>,<NA>,6,0,7869.0,56.2,18.0,False,<NA>,True,0,0.0,189699.0,1,73.0,2,2081.0,65.0,14000.0,2,5,6.0,2737.0,55.9,0,125,184,14,14,5,101,<NA>,10,<NA>,0,2,3,2,4,6,4,7,3,6,100.0,50.0,0,0,218418.0,18696.0,6200.0,14877.0
4,68476807,10400,True,22.45,289.91,25,3,2,104433.0,2015-12-01,0,6,38,25.37,1,1998-06-01,695,3,12,<NA>,12,0,21929.0,64.5,35.0,False,<NA>,False,0,0.0,331730.0,3,84.0,7,9702.0,78.0,34000.0,2,1,10.0,4567.0,77.5,0,128,210,4,4,6,4,12,1,12,0,4,6,5,9,10,7,19,6,12,96.6,60.0,0,0,439570.0,95768.0,20300.0,88097.0
5,68426831,11950,False,13.44,405.18,12,4,1,34000.0,2015-12-01,0,2,10,10.2,0,1987-10-01,690,0,<NA>,<NA>,5,0,8822.0,68.4,6.0,False,<NA>,False,0,0.0,12798.0,1,99.0,0,4522.0,76.0,12900.0,0,0,0.0,844.0,91.0,0,338,54,32,32,0,36,<NA>,<NA>,<NA>,0,2,3,2,2,2,4,4,3,5,100.0,100.0,0,0,16900.0,12798.0,9400.0,4000.0

### Data Imputation

In [6]:
# Impute 'Informative Nulls' with a Constant (Fixed Value) #

# NaN in 'months since...' negative events usually means the event NEVER happened. 
# We impute with 999 so the model treats it as a distinct, safe category.
month_null_cols = [
    'mths_since_last_delinq', 
    'mths_since_last_record',
    'mths_since_recent_bc_dlq', 
    'mths_since_last_major_derog',
    'mths_since_recent_revol_delinq',
    'mths_since_recent_inq' # Inquiries are events, so 999 (no recent inquiries) is fine
]

for col in month_null_cols:
    if col in df.columns:
        df[col] = df[col].fillna(999)
        
# Nan in 'Number of...' usually means the event NEVER happened.
# We impute with 0 because it is a count and 0 makes sense as a value.
number_null_cols = [
    'delinq_2yrs',
    'inq_last_6mths',
    'open_acc',
    'pub_rec',
    'total_acc',
    'acc_now_delinq',
    'tot_coll_amt',
    'open_act_il',
    'open_il_24m',
    'inq_fi',
    'total_cu_tl',
    'acc_open_past_24mths',
    'chargeoff_within_12_mths',
    'mort_acc',
    'num_accts_ever_120_pd',
    'num_actv_bc_tl',
    'num_actv_rev_tl',
    'num_bc_sats',
    'num_bc_tl',
    'num_il_tl',
    'num_op_rev_tl',
    'num_rev_accts',
    'num_rev_tl_bal_gt_0',
    'num_sats',
    'pub_rec_bankruptcies',
    'tax_liens'
]

for col in number_null_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0)

# Impute 'Informative Nulls' with the Mode (Most Frequent Value) - Only one categorical column left
df['emp_length'] = df['emp_length'].fillna(df['emp_length'].mode()[0])

# Impute 'Missing at Random' with the Median (Central Tendency) - Only numerical columns left
cols_with_nulls = df.columns[df.isnull().any()].tolist()

for col in cols_with_nulls:
    median_val = df[col].median(numeric_only=True)
    df[col] = df[col].fillna(median_val)

print_column_info(df)
df.head()

,Total (Null/Total),Percentage (%),Data Type
id,0/1379449,0.0,int64[pyarrow]
loan_amnt,0/1379449,0.0,int64[pyarrow]
term,0/1379449,0.0,bool[pyarrow]
int_rate,0/1379449,0.0,double[pyarrow]
installment,0/1379449,0.0,double[pyarrow]
sub_grade,0/1379449,0.0,int64[pyarrow]
emp_length,0/1379449,0.0,int64[pyarrow]
home_ownership,0/1379449,0.0,int64[pyarrow]
annual_inc,0/1379449,0.0,double[pyarrow]
issue_d,0/1379449,0.0,date32[day][pyarrow]
loan_status,0/1379449,0.0,int64[pyarrow]
purpose,0/1379449,0.0,int64[pyarrow]
addr_state,0/1379449,0.0,object
dti,0/1379449,0.0,double[pyarrow]
delinq_2yrs,0/1379449,0.0,int64[pyarrow]
earliest_cr_line,0/1379449,0.0,date32[day][pyarrow]
fico_range_low,0/1379449,0.0,int64[pyarrow]
inq_last_6mths,0/1379449,0.0,int64[pyarrow]
mths_since_last_delinq,0/1379449,0.0,int64[pyarrow]
mths_since_last_record,0/1379449,0.0,int64[pyarrow]
open_acc,0/1379449,0.0,int64[pyarrow]
pub_rec,0/1379449,0.0,int64[pyarrow]
revol_bal,0/1379449,0.0,double[pyarrow]
revol_util,0/1379449,0.0,double[pyarrow]
total_acc,0/1379449,0.0,double[pyarrow]
initial_list_status,0/1379449,0.0,bool[pyarrow]
mths_since_last_major_derog,0/1379449,0.0,int64[pyarrow]
application_type,0/1379449,0.0,bool[pyarrow]
acc_now_delinq,0/1379449,0.0,int64[pyarrow]
tot_coll_amt,0/1379449,0.0,double[pyarrow]
tot_cur_bal,0/1379449,0.0,double[pyarrow]
open_act_il,0/1379449,0.0,int64[pyarrow]
il_util,0/1379449,0.0,double[pyarrow]
open_rv_24m,0/1379449,0.0,int64[pyarrow]
max_bal_bc,0/1379449,0.0,double[pyarrow]
all_util,0/1379449,0.0,double[pyarrow]
total_rev_hi_lim,0/1379449,0.0,double[pyarrow]
inq_fi,0/1379449,0.0,int64[pyarrow]
total_cu_tl,0/1379449,0.0,int64[pyarrow]
acc_open_past_24mths,0/1379449,0.0,double[pyarrow]
bc_open_to_buy,0/1379449,0.0,double[pyarrow]
bc_util,0/1379449,0.0,double[pyarrow]
chargeoff_within_12_mths,0/1379449,0.0,int64[pyarrow]
mo_sin_old_il_acct,0/1379449,0.0,int64[pyarrow]
mo_sin_old_rev_tl_op,0/1379449,0.0,int64[pyarrow]
mo_sin_rcnt_rev_tl_op,0/1379449,0.0,int64[pyarrow]
mo_sin_rcnt_tl,0/1379449,0.0,int64[pyarrow]
mort_acc,0/1379449,0.0,int64[pyarrow]
mths_since_recent_bc,0/1379449,0.0,int64[pyarrow]
mths_since_recent_bc_dlq,0/1379449,0.0,int64[pyarrow]
mths_since_recent_inq,0/1379449,0.0,int64[pyarrow]
mths_since_recent_revol_delinq,0/1379449,0.0,int64[pyarrow]
num_accts_ever_120_pd,0/1379449,0.0,int64[pyarrow]
num_actv_bc_tl,0/1379449,0.0,int64[pyarrow]
num_actv_rev_tl,0/1379449,0.0,int64[pyarrow]
num_bc_sats,0/1379449,0.0,int64[pyarrow]
num_bc_tl,0/1379449,0.0,int64[pyarrow]
num_il_tl,0/1379449,0.0,int64[pyarrow]
num_op_rev_tl,0/1379449,0.0,int64[pyarrow]
num_rev_accts,0/1379449,0.0,int64[pyarrow]
num_rev_tl_bal_gt_0,0/1379449,0.0,int64[pyarrow]
num_sats,0/1379449,0.0,int64[pyarrow]
pct_tl_nvr_dlq,0/1379449,0.0,double[pyarrow]
percent_bc_gt_75,0/1379449,0.0,double[pyarrow]
pub_rec_bankruptcies,0/1379449,0.0,int64[pyarrow]
tax_liens,0/1379449,0.0,int64[pyarrow]
tot_hi_cred_lim,0/1379449,0.0,double[pyarrow]
total_bal_ex_mort,0/1379449,0.0,double[pyarrow]
total_bc_limit,0/1379449,0.0,double[pyarrow]
total_il_high_credit_limit,0/1379449,0.0,double[pyarrow]

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,issue_d,loan_status,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,mths_since_last_major_derog,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_act_il,il_util,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,acc_open_past_24mths,bc_open_to_buy,bc_util,chargeoff_within_12_mths,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68407277,3600,False,13.99,123.03,13,10,2,55000.0,2015-12-01,0,2,38,5.91,0,2003-08-01,675,1,30,999,7,0,2765.0,29.7,13.0,False,30,False,0,722.0,144904.0,2,36.0,3,722.0,34.0,9300.0,3,1,4.0,1506.0,37.2,0,148,128,3,3,1,4,69,4,69,2,2,4,2,5,3,4,9,4,7,76.9,0.0,0,0,178050.0,7746.0,2400.0,13734.0
1,68355089,24700,False,11.99,820.28,10,10,2,65000.0,2015-12-01,0,11,41,16.06,1,1999-12-01,715,4,6,999,22,0,21470.0,19.2,38.0,False,999,False,0,0.0,204396.0,1,73.0,3,6472.0,29.0,111800.0,0,0,4.0,57830.0,27.1,0,113,192,2,2,4,2,999,0,6,0,5,5,13,17,6,20,27,5,22,97.4,7.7,0,0,314017.0,39475.0,79300.0,24667.0
2,68341763,20000,True,10.78,432.66,8,10,2,63000.0,2015-12-01,0,4,14,10.78,0,2000-08-01,695,0,999,999,6,0,7869.0,56.2,18.0,False,999,True,0,0.0,189699.0,1,73.0,2,2081.0,65.0,14000.0,2,5,6.0,2737.0,55.9,0,125,184,14,14,5,101,999,10,999,0,2,3,2,4,6,4,7,3,6,100.0,50.0,0,0,218418.0,18696.0,6200.0,14877.0
4,68476807,10400,True,22.45,289.91,25,3,2,104433.0,2015-12-01,0,6,38,25.37,1,1998-06-01,695,3,12,999,12,0,21929.0,64.5,35.0,False,999,False,0,0.0,331730.0,3,84.0,7,9702.0,78.0,34000.0,2,1,10.0,4567.0,77.5,0,128,210,4,4,6,4,12,1,12,0,4,6,5,9,10,7,19,6,12,96.6,60.0,0,0,439570.0,95768.0,20300.0,88097.0
5,68426831,11950,False,13.44,405.18,12,4,1,34000.0,2015-12-01,0,2,10,10.2,0,1987-10-01,690,0,999,999,5,0,8822.0,68.4,6.0,False,999,False,0,0.0,12798.0,1,99.0,0,4522.0,76.0,12900.0,0,0,0.0,844.0,91.0,0,338,54,32,32,0,36,999,999,999,0,2,3,2,2,2,4,4,3,5,100.0,100.0,0,0,16900.0,12798.0,9400.0,4000.0

### Convert to Processed .csv

In [7]:
if 'google.colab' in sys.modules:
    pass

else:
    if os.path.exists("../data/processed/processed_data.csv"):
        print("Dataset already exists")

    else:
        df.to_csv("../data/processed/processed_data.csv", index=False)
        print("Dataset saved successfully")

Dataset saved successfully