# Data Preprocessing

### Imports

In [1]:
import sys
import pandas as pd

### Load Dataset

In [ ]:
# Allow the dataset to be loaded with both a Google Colab kernel and a local kernel

# Load the dataset with Google Colab kernel and Drive file
if 'google.colab' in sys.modules:
    # Time (aprox. 1m 30.0s)
    from pydrive2.auth import GoogleAuth
    from pydrive2.drive import GoogleDrive
    from google.colab import auth # type: ignore
    from oauth2client.client import GoogleCredentials

    # Authenticate the User in Google Drive
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)

    # Google Drive ID for public sharing of the dataset
    file_id = "1HLAenC73QhLDCVAvgIw_2Y54Gwcq5S0D"
    file = drive.CreateFile({'id': file_id})
    file.GetContentFile('raw_data.csv')

    # Reading the csv and loading it into a pandas dataframe (Use pyarrow to prevent OOM error when loading)
    df = pd.read_csv("raw_data.csv", engine="pyarrow", dtype_backend="pyarrow")

# Load the dataset with local kernel and local file
else:
    # Time (13th Gen Intel Core i5-1335U: aprox. 3.0s; AMD Ryzen AI 9 HX 370 (24) @ 5.16 GHz: aprox. 1.0s)
    # Reading the csv and loading it into a pandas dataframe (Use pyarrow to prevent OOM error when loading)
    df = pd.read_csv("../data/raw/raw_data.csv", engine="pyarrow", dtype_backend="pyarrow")

# Stop Jupyter Notebook from limiting the output
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Display dataset head
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,None,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68407277,<NA>,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,<NA>,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,<NA>,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,<NA>,<NA>,<NA>,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,68355089,None,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68355089,<NA>,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,<NA>,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.66,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,<NA>,Mar-2019,699.0,695.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,<NA>,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,68341763,None,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68341763,<NA>,home_improvement,<NA>,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,<NA>,<NA>,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.0,2705.92,0.0,0.0,0.0,Jun-2017,15813.3,<NA>,Mar-2019,704.0,700.0,0.0,<NA>,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,<NA>,10.0,<NA>,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,66310712,None,35000.0,35000.0,35000.0,60 months,14.85,829.9,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=66310712,<NA>,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,<NA>,<NA>,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.01,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.9,Apr-2019,Mar-2019,679.0,675.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,<NA>,<NA>,<NA>,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,68476807,None,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68476807,<NA>,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,<NA>,12.0,0.0,21929.0,64.5,35.0,w,0.0,0.0,11740.5,11740.5,10400.0,1340.5,0.0,0.0,0.0,Jul-2016,10128.96,<NA>,Mar-2018,704.0,700.0,0.0,<NA>,1.0,Individual,<NA>,<NA>,<NA>,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cash,N,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

### Delete & Transform Columns & Rows

Display the missing values per column:

In [7]:
def print_column_info(df):
    # Get the total number of rows in the DataFrame
    total_rows = len(df)

    # Create the summary DataFrame
    data = pd.DataFrame({
        'Total (Null/Total)': df.isnull().sum().astype(str) + '/' + str(total_rows),
        'Percentage (%)': df.isnull().mean() * 100,
        'Data Type': df.dtypes
    })

    # Display the result
    display(data)

print_column_info(df)

,Total (Null/Total),Percentage (%),Data Type
id,0/2260701,0.000000,string[pyarrow]
member_id,2260701/2260701,100.000000,null[pyarrow]
loan_amnt,33/2260701,0.001460,double[pyarrow]
funded_amnt,33/2260701,0.001460,double[pyarrow]
funded_amnt_inv,33/2260701,0.001460,double[pyarrow]
term,33/2260701,0.001460,string[pyarrow]
int_rate,33/2260701,0.001460,double[pyarrow]
installment,33/2260701,0.001460,double[pyarrow]
grade,33/2260701,0.001460,string[pyarrow]
sub_grade,33/2260701,0.001460,string[pyarrow]
emp_title,167002/2260701,7.387178,string[pyarrow]
emp_length,146940/2260701,6.499754,string[pyarrow]
home_ownership,33/2260701,0.001460,string[pyarrow]
annual_inc,37/2260701,0.001637,double[pyarrow]
verification_status,33/2260701,0.001460,string[pyarrow]
issue_d,33/2260701,0.001460,string[pyarrow]
loan_status,33/2260701,0.001460,string[pyarrow]
pymnt_plan,33/2260701,0.001460,string[pyarrow]
url,33/2260701,0.001460,string[pyarrow]
desc,2134636/2260701,94.423632,string[pyarrow]
purpose,33/2260701,0.001460,string[pyarrow]
title,23359/2260701,1.033264,string[pyarrow]
zip_code,34/2260701,0.001504,string[pyarrow]
addr_state,33/2260701,0.001460,string[pyarrow]
dti,1744/2260701,0.077144,double[pyarrow]
delinq_2yrs,62/2260701,0.002743,double[pyarrow]
earliest_cr_line,62/2260701,0.002743,string[pyarrow]
fico_range_low,33/2260701,0.001460,double[pyarrow]
fico_range_high,33/2260701,0.001460,double[pyarrow]
inq_last_6mths,63/2260701,0.002787,double[pyarrow]
mths_since_last_delinq,1158535/2260701,51.246715,double[pyarrow]
mths_since_last_record,1901545/2260701,84.113069,double[pyarrow]
open_acc,62/2260701,0.002743,double[pyarrow]
pub_rec,62/2260701,0.002743,double[pyarrow]
revol_bal,33/2260701,0.001460,double[pyarrow]
revol_util,1835/2260701,0.081170,double[pyarrow]
total_acc,62/2260701,0.002743,double[pyarrow]
initial_list_status,33/2260701,0.001460,string[pyarrow]
out_prncp,33/2260701,0.001460,double[pyarrow]
out_prncp_inv,33/2260701,0.001460,double[pyarrow]
total_pymnt,33/2260701,0.001460,double[pyarrow]
total_pymnt_inv,33/2260701,0.001460,double[pyarrow]
total_rec_prncp,33/2260701,0.001460,double[pyarrow]
total_rec_int,33/2260701,0.001460,double[pyarrow]
total_rec_late_fee,33/2260701,0.001460,double[pyarrow]
recoveries,33/2260701,0.001460,double[pyarrow]
collection_recovery_fee,33/2260701,0.001460,double[pyarrow]
last_pymnt_d,2460/2260701,0.108816,string[pyarrow]
last_pymnt_amnt,33/2260701,0.001460,double[pyarrow]
next_pymnt_d,1345343/2260701,59.509993,string[pyarrow]
last_credit_pull_d,105/2260701,0.004645,string[pyarrow]
last_fico_range_high,33/2260701,0.001460,double[pyarrow]
last_fico_range_low,33/2260701,0.001460,double[pyarrow]
collections_12_mths_ex_med,178/2260701,0.007874,double[pyarrow]
mths_since_last_major_derog,1679926/2260701,74.309960,double[pyarrow]
policy_code,33/2260701,0.001460,double[pyarrow]
application_type,33/2260701,0.001460,string[pyarrow]
annual_inc_joint,2139991/2260701,94.660506,double[pyarrow]
dti_joint,2139995/2260701,94.660683,double[pyarrow]
verification_status_joint,2144971/2260701,94.880791,string[pyarrow]
acc_now_delinq,62/2260701,0.002743,double[pyarrow]
tot_coll_amt,70309/2260701,3.110053,double[pyarrow]
tot_cur_bal,70309/2260701,3.110053,double[pyarrow]
open_acc_6m,866163/2260701,38.313912,double[pyarrow]
open_act_il,866162/2260701,38.313868,double[pyarrow]
open_il_12m,866162/2260701,38.313868,double[pyarrow]
open_il_24m,866162/2260701,38.313868,double[pyarrow]
mths_since_rcnt_il,909957/2260701,40.251099,double[pyarrow]
total_bal_il,866162/2260701,38.313868,double[pyarrow]
il_util,1068883/2260701,47.281042,double[pyarrow]
open_rv_12m,866162/2260701,38.313868,double[pyarrow]
open_rv_24m,866162/2260701,38.313868,double[pyarrow]
max_bal_bc,866162/2260701,38.313868,double[pyarrow]
all_util,866381/2260701,38.323555,double[pyarrow]
total_rev_hi_lim,70309/2260701,3.110053,double[pyarrow]
inq_fi,866162/2260701,38.313868,double[pyarrow]
total_cu_tl,866163/2260701,38.313912,double[pyarrow]
inq_last_12m,866163/2260701,38.313912,double[pyarrow]
acc_open_past_24mths,50063/2260701,2.214490,double[pyarrow]
avg_cur_bal,70379/2260701,3.113149,double[pyarrow]
bc_open_to_buy,74968/2260701,3.316140,double[pyarrow]
bc_util,76104/2260701,3.366389,double[pyarrow]
chargeoff_within_12_mths,178/2260701,0.007874,double[pyarrow]
delinq_amnt,62/2260701,0.002743,double[pyarrow]
mo_sin_old_il_acct,139104/2260701,6.153136,double[pyarrow]
mo_sin_old_rev_tl_op,70310/2260701,3.110097,double[pyarrow]
mo_sin_rcnt_rev_tl_op,70310/2260701,3.110097,double[pyarrow]
mo_sin_rcnt_tl,70309/2260701,3.110053,double[pyarrow]
mort_acc,50063/2260701,2.214490,double[pyarrow]
mths_since_recent_bc,73445/2260701,3.248771,double[pyarrow]
mths_since_recent_bc_dlq,1741000/2260701,77.011511,double[pyarrow]
mths_since_recent_inq,295468/2260701,13.069751,double[pyarrow]
mths_since_recent_revol_delinq,1520342/2260701,67.250910,double[pyarrow]
num_accts_ever_120_pd,70309/2260701,3.110053,double[pyarrow]
num_actv_bc_tl,70309/2260701,3.110053,double[pyarrow]
num_actv_rev_tl,70309/2260701,3.110053,double[pyarrow]
num_bc_sats,58623/2260701,2.593134,double[pyarrow]
num_bc_tl,70309/2260701,3.110053,double[pyarrow]
num_il_tl,70309/2260701,3.110053,double[pyarrow]
num_op_rev_tl,70309/2260701,3.110053,double[pyarrow]
num_rev_accts,70310/2260701,3.110097,double[pyarrow]
num_rev_tl_bal_gt_0,70309/2260701,3.110053,double[pyarrow]
num_sats,58623/2260701,2.593134,double[pyarrow]
num_tl_120dpd_2m,153690/2260701,6.798334,double[pyarrow]
num_tl_30dpd,70309/2260701,3.110053,double[pyarrow]
num_tl_90g_dpd_24m,70309/2260701,3.110053,double[pyarrow]
num_tl_op_past_12m,70309/2260701,3.110053,double[pyarrow]
pct_tl_nvr_dlq,70464/2260701,3.116909,double[pyarrow]
percent_bc_gt_75,75412/2260701,3.335779,double[pyarrow]
pub_rec_bankruptcies,1398/2260701,0.061839,double[pyarrow]
tax_liens,138/2260701,0.006104,double[pyarrow]
tot_hi_cred_lim,70309/2260701,3.110053,double[pyarrow]
total_bal_ex_mort,50063/2260701,2.214490,double[pyarrow]
total_bc_limit,50063/2260701,2.214490,double[pyarrow]
total_il_high_credit_limit,70309/2260701,3.110053,double[pyarrow]
revol_bal_joint,2152681/2260701,95.221836,double[pyarrow]
sec_app_fico_range_low,2152680/2260701,95.221792,double[pyarrow]
sec_app_fico_range_high,2152680/2260701,95.221792,double[pyarrow]
sec_app_earliest_cr_line,2152680/2260701,95.221792,string[pyarrow]
sec_app_inq_last_6mths,2152680/2260701,95.221792,double[pyarrow]
sec_app_mort_acc,2152680/2260701,95.221792,double[pyarrow]
sec_app_open_acc,2152680/2260701,95.221792,double[pyarrow]
sec_app_revol_util,2154517/2260701,95.303050,double[pyarrow]
sec_app_open_act_il,2152680/2260701,95.221792,double[pyarrow]
sec_app_num_rev_accts,2152680/2260701,95.221792,double[pyarrow]
sec_app_chargeoff_within_12_mths,2152680/2260701,95.221792,double[pyarrow]
sec_app_collections_12_mths_ex_med,2152680/2260701,95.221792,double[pyarrow]
sec_app_mths_since_last_major_derog,2224759/2260701,98.410139,double[pyarrow]
hardship_flag,33/2260701,0.001460,string[pyarrow]
hardship_type,2249784/2260701,99.517097,string[pyarrow]
hardship_reason,2249784/2260701,99.517097,string[pyarrow]
hardship_status,2249784/2260701,99.517097,string[pyarrow]
deferral_term,2249784/2260701,99.517097,double[pyarrow]
hardship_amount,2249784/2260701,99.517097,double[pyarrow]
hardship_start_date,2249784/2260701,99.517097,string[pyarrow]
hardship_end_date,2249784/2260701,99.517097,string[pyarrow]
payment_plan_start_date,2249784/2260701,99.517097,string[pyarrow]
hardship_length,2249784/2260701,99.517097,double[pyarrow]
hardship_dpd,2249784/2260701,99.517097,double[pyarrow]
hardship_loan_status,2249784/2260701,99.517097,string[pyarrow]
orig_projected_additional_accrued_interest,2252050/2260701,99.617331,double[pyarrow]
hardship_payoff_balance_amount,2249784/2260701,99.517097,double[pyarrow]
hardship_last_payment_amount,2249784/2260701,99.517097,double[pyarrow]
disbursement_method,33/2260701,0.001460,string[pyarrow]
debt_settlement_flag,33/2260701,0.001460,string[pyarrow]
debt_settlement_flag_date,2226455/2260701,98.485160,string[pyarrow]
settlement_status,2226455/2260701,98.485160,string[pyarrow]
settlement_date,2226455/2260701,98.485160,string[pyarrow]
settlement_amount,2226455/2260701,98.485160,double[pyarrow]
settlement_percentage,2226455/2260701,98.485160,double[pyarrow]
settlement_term,2226455/2260701,98.485160,double[pyarrow]

In [ ]:
'''
Total (Null/Total)	Percentage (%)	Data Type
id	0/2260701	0.000000	string[pyarrow] # Change data type to int
member_id	2260701/2260701	100.000000	null[pyarrow] # Delete
loan_amnt	33/2260701	0.001460	double[pyarrow] # Nothing
funded_amnt	33/2260701	0.001460	double[pyarrow] # Delete, same shit as loan amount
funded_amnt_inv	33/2260701	0.001460	double[pyarrow] # Delete, same shit as loan amount
term	33/2260701	0.001460	string[pyarrow] # Convert to 0-1 and change data type to bool
int_rate	33/2260701	0.001460	double[pyarrow] # Nothing
installment	33/2260701	0.001460	double[pyarrow] # Nothing
grade	33/2260701	0.001460	string[pyarrow] # Delete, subgrade is same with more detail
sub_grade	33/2260701	0.001460	string[pyarrow] # Transform to numbers and change data type to int
emp_title	167002/2260701	7.387178	string[pyarrow] # Delete, because not usable
emp_length	146940/2260701	6.499754	string[pyarrow] # Transform to numbers and change data type to int
home_ownership	33/2260701	0.001460	string[pyarrow] # Transform to numbers and change data type to int
annual_inc	37/2260701	0.001637	double[pyarrow] # Nothing
verification_status	33/2260701	0.001460	string[pyarrow] # Delete
issue_d	33/2260701	0.001460	string[pyarrow] # Change data type to date32
loan_status	33/2260701	0.001460	string[pyarrow] # Delete all rows with current, transform to numbers and change data type to int
pymnt_plan	33/2260701	0.001460	string[pyarrow] # Delete (Data leakage)
url	33/2260701	0.001460	string[pyarrow] # Delete
desc	2134636/2260701	94.423632	string[pyarrow] # Delete
purpose	33/2260701	0.001460	string[pyarrow] # Transform to numbers and change data type to int
title	23359/2260701	1.033264	string[pyarrow] # Delete, purpose is same, with less detail, making it usable
zip_code	34/2260701	0.001504	string[pyarrow] # Delete, because not usable
addr_state	33/2260701	0.001460	string[pyarrow] # Transform to numbers and change data type to int
dti	1744/2260701	0.077144	double[pyarrow] # Nothing
delinq_2yrs	62/2260701	0.002743	double[pyarrow] # Nothing
earliest_cr_line	62/2260701	0.002743	string[pyarrow] # Change data type to date32
fico_range_low	33/2260701	0.001460	double[pyarrow] # Nothing
fico_range_high	33/2260701	0.001460	double[pyarrow] # Delete, almost same shit as fico_range_low
inq_last_6mths	63/2260701	0.002787	double[pyarrow] # Nothing
mths_since_last_delinq	1158535/2260701	51.246715	double[pyarrow] # Nothing
mths_since_last_record	1901545/2260701	84.113069	double[pyarrow] # Nothing
open_acc	62/2260701	0.002743	double[pyarrow] # Nothing
pub_rec	62/2260701	0.002743	double[pyarrow] # Nothing
revol_bal	33/2260701	0.001460	double[pyarrow] # Nothing
revol_util	1835/2260701	0.081170	double[pyarrow] # Nothing
total_acc	62/2260701	0.002743	double[pyarrow] # Nothing
initial_list_status	33/2260701	0.001460	string[pyarrow] # Convert to 0-1 and change data type to bool
out_prncp	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
out_prncp_inv	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
total_pymnt	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
total_pymnt_inv	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
total_rec_prncp	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
total_rec_int	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
total_rec_late_fee	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
recoveries	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
collection_recovery_fee	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
last_pymnt_d	2460/2260701	0.108816	string[pyarrow] # Delete (Data leakage)
last_pymnt_amnt	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
next_pymnt_d	1345343/2260701	59.509993	string[pyarrow] # Delete (Data leakage)
last_credit_pull_d	105/2260701	0.004645	string[pyarrow] # Delete (Data leakage)
last_fico_range_high	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
last_fico_range_low	33/2260701	0.001460	double[pyarrow] # Delete (Data leakage)
collections_12_mths_ex_med	178/2260701	0.007874	double[pyarrow] # Delete (Data leakage)
mths_since_last_major_derog	1679926/2260701	74.309960	double[pyarrow] # Nothing
policy_code	33/2260701	0.001460	double[pyarrow] # Delete
application_type	33/2260701	0.001460	string[pyarrow] # Convert to 0-1 and change data type to bool
annual_inc_joint	2139991/2260701	94.660506	double[pyarrow] # Delete
dti_joint	2139995/2260701	94.660683	double[pyarrow] # Delete
verification_status_joint	2144971/2260701	94.880791	string[pyarrow] # Delete
acc_now_delinq	62/2260701	0.002743	double[pyarrow] # Nothing
tot_coll_amt	70309/2260701	3.110053	double[pyarrow] # Nothing
tot_cur_bal	70309/2260701	3.110053	double[pyarrow] # Nothing
open_acc_6m	866163/2260701	38.313912	double[pyarrow] # Nothing
open_act_il	866162/2260701	38.313868	double[pyarrow] # Nothing
open_il_12m	866162/2260701	38.313868	double[pyarrow] # Delete, same shit as open_act_il
open_il_24m	866162/2260701	38.313868	double[pyarrow] # Delete, same shit as open_act_il
mths_since_rcnt_il	909957/2260701	40.251099	double[pyarrow] # Delete, same shit as open_act_il
total_bal_il	866162/2260701	38.313868	double[pyarrow] # Delete, same shit as il_util
il_util	1068883/2260701	47.281042	double[pyarrow] # Nothing
open_rv_12m	866162/2260701	38.313868	double[pyarrow] # Delete, same shit as open_rv_24m
open_rv_24m	866162/2260701	38.313868	double[pyarrow] # Nothing
max_bal_bc	866162/2260701	38.313868	double[pyarrow] # Nothing
all_util	866381/2260701	38.323555	double[pyarrow] # Nothing
total_rev_hi_lim	70309/2260701	3.110053	double[pyarrow] # Nothing
inq_fi	866162/2260701	38.313868	double[pyarrow] # Nothing
total_cu_tl	866163/2260701	38.313912	double[pyarrow] # Nothing
inq_last_12m	866163/2260701	38.313912	double[pyarrow] # Nothing
acc_open_past_24mths	50063/2260701	2.214490	double[pyarrow] # Nothing
avg_cur_bal	70379/2260701	3.113149	double[pyarrow] # Delete, same shit as tot_cur_bal
bc_open_to_buy	74968/2260701	3.316140	double[pyarrow] # Nothing
bc_util	76104/2260701	3.366389	double[pyarrow] # Nothing
chargeoff_within_12_mths	178/2260701	0.007874	double[pyarrow] # Nothing
delinq_amnt	62/2260701	0.002743	double[pyarrow] # Delete (Data leakage)
mo_sin_old_il_acct	139104/2260701	6.153136	double[pyarrow] # Nothing
mo_sin_old_rev_tl_op	70310/2260701	3.110097	double[pyarrow] # Nothing
mo_sin_rcnt_rev_tl_op	70310/2260701	3.110097	double[pyarrow] # Nothing
mo_sin_rcnt_tl	70309/2260701	3.110053	double[pyarrow] # Nothing
mort_acc	50063/2260701	2.214490	double[pyarrow] # Nothing
mths_since_recent_bc	73445/2260701	3.248771	double[pyarrow] # Nothing
mths_since_recent_bc_dlq	1741000/2260701	77.011511	double[pyarrow] # Nothing
mths_since_recent_inq	295468/2260701	13.069751	double[pyarrow] # Nothing
mths_since_recent_revol_delinq	1520342/2260701	67.250910	double[pyarrow] # Nothing
num_accts_ever_120_pd	70309/2260701	3.110053	double[pyarrow] # Nothing
num_actv_bc_tl	70309/2260701	3.110053	double[pyarrow] # Nothing
num_actv_rev_tl	70309/2260701	3.110053	double[pyarrow] # Nothing
num_bc_sats	58623/2260701	2.593134	double[pyarrow] # Nothing
num_bc_tl	70309/2260701	3.110053	double[pyarrow] # Nothing
num_il_tl	70309/2260701	3.110053	double[pyarrow] # Nothing
num_op_rev_tl	70309/2260701	3.110053	double[pyarrow] # Nothing
num_rev_accts	70310/2260701	3.110097	double[pyarrow] # Nothing
num_rev_tl_bal_gt_0	70309/2260701	3.110053	double[pyarrow] # Nothing
num_sats	58623/2260701	2.593134	double[pyarrow] # Nothing
num_tl_120dpd_2m	153690/2260701	6.798334	double[pyarrow] # Delete (Data leakage)
num_tl_30dpd	70309/2260701	3.110053	double[pyarrow] # Delete (Data leakage)
num_tl_90g_dpd_24m	70309/2260701	3.110053	double[pyarrow] # Delete (Data leakage)
num_tl_op_past_12m	70309/2260701	3.110053	double[pyarrow] # Delete (Data leakage)
pct_tl_nvr_dlq	70464/2260701	3.116909	double[pyarrow] # Nothing
percent_bc_gt_75	75412/2260701	3.335779	double[pyarrow] # Nothing
pub_rec_bankruptcies	1398/2260701	0.061839	double[pyarrow] # Nothing
tax_liens	138/2260701	0.006104	double[pyarrow] # Nothing
tot_hi_cred_lim	70309/2260701	3.110053	double[pyarrow] # Nothing
total_bal_ex_mort	50063/2260701	2.214490	double[pyarrow] # Nothing
total_bc_limit	50063/2260701	2.214490	double[pyarrow] # Nothing
total_il_high_credit_limit	70309/2260701	3.110053	double[pyarrow] # Nothing
revol_bal_joint	2152681/2260701	95.221836	double[pyarrow] # Delete
sec_app_fico_range_low	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_fico_range_high	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_earliest_cr_line	2152680/2260701	95.221792	string[pyarrow] # Delete
sec_app_inq_last_6mths	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_mort_acc	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_open_acc	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_revol_util	2154517/2260701	95.303050	double[pyarrow] # Delete
sec_app_open_act_il	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_num_rev_accts	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_chargeoff_within_12_mths	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_collections_12_mths_ex_med	2152680/2260701	95.221792	double[pyarrow] # Delete
sec_app_mths_since_last_major_derog	2224759/2260701	98.410139	double[pyarrow] # Delete
hardship_flag	33/2260701	0.001460	string[pyarrow] # Delete (Data leakage)
hardship_type	2249784/2260701	99.517097	string[pyarrow] # Delete
hardship_reason	2249784/2260701	99.517097	string[pyarrow] # Delete
hardship_status	2249784/2260701	99.517097	string[pyarrow] # Delete
deferral_term	2249784/2260701	99.517097	double[pyarrow] # Delete
hardship_amount	2249784/2260701	99.517097	double[pyarrow] # Delete
hardship_start_date	2249784/2260701	99.517097	string[pyarrow] # Delete
hardship_end_date	2249784/2260701	99.517097	string[pyarrow] # Delete
payment_plan_start_date	2249784/2260701	99.517097	string[pyarrow] # Delete
hardship_length	2249784/2260701	99.517097	double[pyarrow] # Delete
hardship_dpd	2249784/2260701	99.517097	double[pyarrow] # Delete
hardship_loan_status	2249784/2260701	99.517097	string[pyarrow]
orig_projected_additional_accrued_interest	2252050/2260701	99.617331	double[pyarrow] # Delete
hardship_payoff_balance_amount	2249784/2260701	99.517097	double[pyarrow] # Delete
hardship_last_payment_amount	2249784/2260701	99.517097	double[pyarrow] # Delete
disbursement_method	33/2260701	0.001460	string[pyarrow] # Delete (Data leakage)
debt_settlement_flag	33/2260701	0.001460	string[pyarrow] # Delete (Data leakage)
debt_settlement_flag_date	2226455/2260701	98.485160	string[pyarrow] # Delete
settlement_status	2226455/2260701	98.485160	string[pyarrow] # Delete
settlement_date	2226455/2260701	98.485160	string[pyarrow] # Delete
settlement_amount	2226455/2260701	98.485160	double[pyarrow] # Delete
settlement_percentage	2226455/2260701	98.485160	double[pyarrow] # Delete
settlement_term	2226455/2260701	98.485160	double[pyarrow] # Delete
'''

''